$(document).ready(function() {
  $("#retrieve-company-Walmart").click(function()
  {var displayResources = $("#display-company-Walmart");
  +displayResources.text("Loading data from JSON source...");
  $.ajax(
    {type: "GET",
    url: "https://api.iextrading.com/1.0/stock/WMT/company",
    success: function(result) {
      console.log(result);
      var output ="<table><thead><tr><th>symbol</th><th>companyName</th><th>exchange</th><th>industry</th><th>website</th><th>description</th><th>CEO</th><th>issuetype</th><th>sector</th><th>tags</th></thead><tbody>";
      output +="<tr><td>" +result.symbols+"</td><td>" +result.companyName+"</td><td>" +result.exchange +"</td><td>" +result.industry+"</td><td>" +result.website+"</td><td>" +result.description+"</td><td>" +result.CEO+"</td><td>" +result.issueType+"</td><td>" +result.sector+"</td></tr>";output += "</tbody></table>";
      displayResources.html(output);
      $("table").addClass("table");}
    });
  });


$("#retrieve-company-UnitedHealth").click(function() {var displayResources = $("#display-company-UnitedHealth"); +displayResources.text("Loading data from JSON source...");$.ajax({type: "GET",url: "https://api.iextrading.com/1.0/stock/UNH/company",success: function(result) {console.log(result);var output ="<table><thead><tr><th>symbol</th><th>companyName</th><th>exchange</th><th>industry</th><th>website</th><th>description</th><th>CEO</th><th>issuetype</th><th>sector</th><th>tags</th></thead><tbody>";output +="<tr><td>" +result.symbol+"</td><td>" +result.companyName+"</td><td>" +result.exchange +"</td><td>" +result.industry+"</td><td>" +result.website+"</td><td>" +result.description+"</td><td>" +result.CEO+"</td><td>" +result.issueType+"</td><td>" +result.sector+"</td></tr>";output += "</tbody></table>";displayResources.html(output);$("table").addClass("table");}});});


$("#retrieve-company-Apple").click(function() {var displayResources = $("#display-company-Apple"); +displayResources.text("Loading data from JSON source...");$.ajax({type: "GET",url: "https://api.iextrading.com/1.0/stock/AAPL/company",success: function(result) {console.log(result);var output ="<table><thead><tr><th>symbol</th><th>companyName</th><th>exchange</th><th>industry</th><th>website</th><th>description</th><th>CEO</th><th>issuetype</th><th>sector</th><th>tags</th></thead><tbody>";output +="<tr><td>" +result.symbol+"</td><td>" +result.companyName+"</td><td>" +result.exchange +"</td><td>" +result.industry+"</td><td>" +result.website+"</td><td>" +result.description+"</td><td>" +result.CEO+"</td><td>" +result.issueType+"</td><td>" +result.sector+"</td></tr>";output += "</tbody></table>";displayResources.html(output);$("table").addClass("table");}});});


$("#retrieve-company-Mastercard").click(function() {var displayResources = $("#display-company-Mastercard"); +displayResources.text("Loading data from JSON source...");$.ajax({type: "GET",url: "https://api.iextrading.com/1.0/stock/MA/company",success: function(result) {console.log(result);var output ="<table><thead><tr><th>symbol</th><th>companyName</th><th>exchange</th><th>industry</th><th>website</th><th>description</th><th>CEO</th><th>issuetype</th><th>sector</th><th>tags</th></thead><tbody>";output +="<tr><td>" +result.symbol+"</td><td>" +result.companyName+"</td><td>" +result.exchange +"</td><td>" +result.industry+"</td><td>" +result.website+"</td><td>" +result.description+"</td><td>" +result.CEO+"</td><td>" +result.issueType+"</td><td>" +result.sector+"</td></tr>";output += "</tbody></table>";displayResources.html(output);$("table").addClass("table");}});});


$("#retrieve-company-LululemonAthletica").click(function() {var displayResources = $("#display-company-LululemonAthletica"); +displayResources.text("Loading data from JSON source...");$.ajax({type: "GET",url: "https://api.iextrading.com/1.0/stock/LULU/company",success: function(result) {console.log(result);var output ="<table><thead><tr><th>symbol</th><th>companyName</th><th>exchange</th><th>industry</th><th>website</th><th>description</th><th>CEO</th><th>issuetype</th><th>sector</th><th>tags</th></thead><tbody>";output +="<tr><td>" +result.symbol+"</td><td>" +result.companyName+"</td><td>" +result.exchange +"</td><td>" +result.industry+"</td><td>" +result.website+"</td><td>" +result.description+"</td><td>" +result.CEO+"</td><td>" +result.issueType+"</td><td>" +result.sector+"</td></tr>";output += "</tbody></table>";displayResources.html(output);$("table").addClass("table");}});});


$("#retrieve-company-BestBuy").click(function() {var displayResources = $("#display-company-BestBuy"); +displayResources.text("Loading data from JSON source...");$.ajax({type: "GET",url: "https://api.iextrading.com/1.0/stock/BBY/company",success: function(result) {console.log(result);var output ="<table><thead><tr><th>symbol</th><th>companyName</th><th>exchange</th><th>industry</th><th>website</th><th>description</th><th>CEO</th><th>issuetype</th><th>sector</th><th>tags</th></thead><tbody>";output +="<tr><td>" +result.symbol+"</td><td>" +result.companyName+"</td><td>" +result.exchange +"</td><td>" +result.industry+"</td><td>" +result.website+"</td><td>" +result.description+"</td><td>" +result.CEO+"</td><td>" +result.issueType+"</td><td>" +result.sector+"</td></tr>";output += "</tbody></table>";displayResources.html(output);$("table").addClass("table");}});});


$("#retrieve-company-Yum").click(function() {var displayResources = $("#display-company-Yum"); +displayResources.text("Loading data from JSON source...");$.ajax({type: "GET",url: "https://api.iextrading.com/1.0/stock/YUM/company",success: function(result) {console.log(result);var output ="<table><thead><tr><th>symbol</th><th>companyName</th><th>exchange</th><th>industry</th><th>website</th><th>description</th><th>CEO</th><th>issuetype</th><th>sector</th><th>tags</th></thead><tbody>";output +="<tr><td>" +result.symbol+"</td><td>" +result.companyName+"</td><td>" +result.exchange +"</td><td>" +result.industry+"</td><td>" +result.website+"</td><td>" +result.description+"</td><td>" +result.CEO+"</td><td>" +result.issueType+"</td><td>" +result.sector+"</td></tr>";output += "</tbody></table>";displayResources.html(output);$("table").addClass("table");}});});


$("#retrieve-company-TJX").click(function() {var displayResources = $("#display-company-TJX"); +displayResources.text("Loading data from JSON source...");$.ajax({type: "GET",url: "https://api.iextrading.com/1.0/stock/TJX/company",success: function(result) {console.log(result);var output ="<table><thead><tr><th>symbol</th><th>companyName</th><th>exchange</th><th>industry</th><th>website</th><th>description</th><th>CEO</th><th>issuetype</th><th>sector</th><th>tags</th></thead><tbody>";output +="<tr><td>" +result.symbol+"</td><td>" +result.companyName+"</td><td>" +result.exchange +"</td><td>" +result.industry+"</td><td>" +result.website+"</td><td>" +result.description+"</td><td>" +result.CEO+"</td><td>" +result.issueType+"</td><td>" +result.sector+"</td></tr>";output += "</tbody></table>";displayResources.html(output);$("table").addClass("table");}});});


$("#retrieve-company-Sony").click(function() {var displayResources = $("#display-company-Sony"); +displayResources.text("Loading data from JSON source...");$.ajax({type: "GET",url: "https://api.iextrading.com/1.0/stock/SNE/company",success: function(result) {console.log(result);var output ="<table><thead><tr><th>symbol</th><th>companyName</th><th>exchange</th><th>industry</th><th>website</th><th>description</th><th>CEO</th><th>issuetype</th><th>sector</th><th>tags</th></thead><tbody>";output +="<tr><td>" +result.symbol+"</td><td>" +result.companyName+"</td><td>" +result.exchange +"</td><td>" +result.industry+"</td><td>" +result.website+"</td><td>" +result.description+"</td><td>" +result.CEO+"</td><td>" +result.issueType+"</td><td>" +result.sector+"</td></tr>";output += "</tbody></table>";displayResources.html(output);$("table").addClass("table");}});});


$("#retrieve-company-Costco").click(function() {var displayResources = $("#display-company-Costco"); +displayResources.text("Loading data from JSON source...");$.ajax({type: "GET",url: "https://api.iextrading.com/1.0/stock/COST/company",success: function(result) {console.log(result);var output ="<table><thead><tr><th>symbol</th><th>companyName</th><th>exchange</th><th>industry</th><th>website</th><th>description</th><th>CEO</th><th>issuetype</th><th>sector</th><th>tags</th></thead><tbody>";output +="<tr><td>" +result.symbol+"</td><td>" +result.companyName+"</td><td>" +result.exchange +"</td><td>" +result.industry+"</td><td>" +result.website+"</td><td>" +result.description+"</td><td>" +result.CEO+"</td><td>" +result.issueType+"</td><td>" +result.sector+"</td></tr>";output += "</tbody></table>";displayResources.html(output);$("table").addClass("table");}});});


$("#retrieve-company-Conocophillips").click(function() {var displayResources = $("#display-company-Conocophillips"); +displayResources.text("Loading data from JSON source...");$.ajax({type: "GET",url: "https://api.iextrading.com/1.0/stock/COP/company",success: function(result) {console.log(result);var output ="<table><thead><tr><th>symbol</th><th>companyName</th><th>exchange</th><th>industry</th><th>website</th><th>description</th><th>CEO</th><th>issuetype</th><th>sector</th><th>tags</th></thead><tbody>";output +="<tr><td>" +result.symbol+"</td><td>" +result.companyName+"</td><td>" +result.exchange +"</td><td>" +result.industry+"</td><td>" +result.website+"</td><td>" +result.description+"</td><td>" +result.CEO+"</td><td>" +result.issueType+"</td><td>" +result.sector+"</td></tr>";output += "</tbody></table>";displayResources.html(output);$("table").addClass("table");}});});


$("#retrieve-company-SynchronyFinancial").click(function() {var displayResources = $("#display-company-SynchronyFinancial"); +displayResources.text("Loading data from JSON source...");$.ajax({type: "GET",url: "https://api.iextrading.com/1.0/stock/SYF/company",success: function(result) {console.log(result);var output ="<table><thead><tr><th>symbol</th><th>companyName</th><th>exchange</th><th>industry</th><th>website</th><th>description</th><th>CEO</th><th>issuetype</th><th>sector</th><th>tags</th></thead><tbody>";output +="<tr><td>" +result.symbol+"</td><td>" +result.companyName+"</td><td>" +result.exchange +"</td><td>" +result.industry+"</td><td>" +result.website+"</td><td>" +result.description+"</td><td>" +result.CEO+"</td><td>" +result.issueType+"</td><td>" +result.sector+"</td></tr>";output += "</tbody></table>";displayResources.html(output);$("table").addClass("table");}});});


$("#retrieve-company-CapitalOne").click(function() {var displayResources = $("#display-company-CapitalOne"); +displayResources.text("Loading data from JSON source...");$.ajax({type: "GET",url: "https://api.iextrading.com/1.0/stock/COF/company",success: function(result) {console.log(result);var output ="<table><thead><tr><th>symbol</th><th>companyName</th><th>exchange</th><th>industry</th><th>website</th><th>description</th><th>CEO</th><th>issuetype</th><th>sector</th><th>tags</th></thead><tbody>";output +="<tr><td>" +result.symbol+"</td><td>" +result.companyName+"</td><td>" +result.exchange +"</td><td>" +result.industry+"</td><td>" +result.website+"</td><td>" +result.description+"</td><td>" +result.CEO+"</td><td>" +result.issueType+"</td><td>" +result.sector+"</td></tr>";output += "</tbody></table>";displayResources.html(output);$("table").addClass("table");}});});


$("#retrieve-company-BankOfMontreal").click(function() {var displayResources = $("#display-company-BankOfMontreal"); +displayResources.text("Loading data from JSON source...");$.ajax({type: "GET",url: "https://api.iextrading.com/1.0/stock/BMO/company",success: function(result) {console.log(result);var output ="<table><thead><tr><th>symbol</th><th>companyName</th><th>exchange</th><th>industry</th><th>website</th><th>description</th><th>CEO</th><th>issuetype</th><th>sector</th><th>tags</th></thead><tbody>";output +="<tr><td>" +result.symbol+"</td><td>" +result.companyName+"</td><td>" +result.exchange +"</td><td>" +result.industry+"</td><td>" +result.website+"</td><td>" +result.description+"</td><td>" +result.CEO+"</td><td>" +result.issueType+"</td><td>" +result.sector+"</td></tr>";output += "</tbody></table>";displayResources.html(output);$("table").addClass("table");}});});


$("#retrieve-company-BristolMyers").click(function() {var displayResources = $("#display-company-BristolMyers"); +displayResources.text("Loading data from JSON source...");$.ajax({type: "GET",url: "https://api.iextrading.com/1.0/stock/BMY/company",success: function(result) {console.log(result);var output ="<table><thead><tr><th>symbol</th><th>companyName</th><th>exchange</th><th>industry</th><th>website</th><th>description</th><th>CEO</th><th>issuetype</th><th>sector</th><th>tags</th></thead><tbody>";output +="<tr><td>" +result.symbol+"</td><td>" +result.companyName+"</td><td>" +result.exchange +"</td><td>" +result.industry+"</td><td>" +result.website+"</td><td>" +result.description+"</td><td>" +result.CEO+"</td><td>" +result.issueType+"</td><td>" +result.sector+"</td></tr>";output += "</tbody></table>";displayResources.html(output);$("table").addClass("table");}});});


$("#retrieve-company-Raytheon").click(function() {var displayResources = $("#display-company-Raytheon"); +displayResources.text("Loading data from JSON source...");$.ajax({type: "GET",url: "https://api.iextrading.com/1.0/stock/RTN/company",success: function(result) {console.log(result);var output ="<table><thead><tr><th>symbol</th><th>companyName</th><th>exchange</th><th>industry</th><th>website</th><th>description</th><th>CEO</th><th>issuetype</th><th>sector</th><th>tags</th></thead><tbody>";output +="<tr><td>" +result.symbol+"</td><td>" +result.companyName+"</td><td>" +result.exchange +"</td><td>" +result.industry+"</td><td>" +result.website+"</td><td>" +result.description+"</td><td>" +result.CEO+"</td><td>" +result.issueType+"</td><td>" +result.sector+"</td></tr>";output += "</tbody></table>";displayResources.html(output);$("table").addClass("table");}});});


$("#retrieve-company-Dell").click(function() {var displayResources = $("#display-company-Dell"); +displayResources.text("Loading data from JSON source...");$.ajax({type: "GET",url: "https://api.iextrading.com/1.0/stock/DVMT/company",success: function(result) {console.log(result);var output ="<table><thead><tr><th>symbol</th><th>companyName</th><th>exchange</th><th>industry</th><th>website</th><th>description</th><th>CEO</th><th>issuetype</th><th>sector</th><th>tags</th></thead><tbody>";output +="<tr><td>" +result.symbol+"</td><td>" +result.companyName+"</td><td>" +result.exchange +"</td><td>" +result.industry+"</td><td>" +result.website+"</td><td>" +result.description+"</td><td>" +result.CEO+"</td><td>" +result.issueType+"</td><td>" +result.sector+"</td></tr>";output += "</tbody></table>";displayResources.html(output);$("table").addClass("table");}});});


$("#retrieve-company-HewlettPackard").click(function() {var displayResources = $("#display-company-HewlettPackard"); +displayResources.text("Loading data from JSON source...");$.ajax({type: "GET",url: "https://api.iextrading.com/1.0/stock/HPE/company",success: function(result) {console.log(result);var output ="<table><thead><tr><th>symbol</th><th>companyName</th><th>exchange</th><th>industry</th><th>website</th><th>description</th><th>CEO</th><th>issuetype</th><th>sector</th><th>tags</th></thead><tbody>";output +="<tr><td>" +result.symbol+"</td><td>" +result.companyName+"</td><td>" +result.exchange +"</td><td>" +result.industry+"</td><td>" +result.website+"</td><td>" +result.description+"</td><td>" +result.CEO+"</td><td>" +result.issueType+"</td><td>" +result.sector+"</td></tr>";output += "</tbody></table>";displayResources.html(output);$("table").addClass("table");}});});


$("#retrieve-company-HP").click(function() {var displayResources = $("#display-company-HP"); +displayResources.text("Loading data from JSON source...");$.ajax({type: "GET",url: "https://api.iextrading.com/1.0/stock/HPQ/company",success: function(result) {console.log(result);var output ="<table><thead><tr><th>symbol</th><th>companyName</th><th>exchange</th><th>industry</th><th>website</th><th>description</th><th>CEO</th><th>issuetype</th><th>sector</th><th>tags</th></thead><tbody>";output +="<tr><td>" +result.symbol+"</td><td>" +result.companyName+"</td><td>" +result.exchange +"</td><td>" +result.industry+"</td><td>" +result.website+"</td><td>" +result.description+"</td><td>" +result.CEO+"</td><td>" +result.issueType+"</td><td>" +result.sector+"</td></tr>";output += "</tbody></table>";displayResources.html(output);$("table").addClass("table");}});});


$("#retrieve-company-Intuit").click(function() {var displayResources = $("#display-company-Intuit"); +displayResources.text("Loading data from JSON source...");$.ajax({type: "GET",url: "https://api.iextrading.com/1.0/stock/INTU/company",success: function(result) {console.log(result);var output ="<table><thead><tr><th>symbol</th><th>companyName</th><th>exchange</th><th>industry</th><th>website</th><th>description</th><th>CEO</th><th>issuetype</th><th>sector</th><th>tags</th></thead><tbody>";output +="<tr><td>" +result.symbol+"</td><td>" +result.companyName+"</td><td>" +result.exchange +"</td><td>" +result.industry+"</td><td>" +result.website+"</td><td>" +result.description+"</td><td>" +result.CEO+"</td><td>" +result.issueType+"</td><td>" +result.sector+"</td></tr>";output += "</tbody></table>";displayResources.html(output);$("table").addClass("table");}});});


$("#retrieve-company-Bandwidth").click(function() {var displayResources = $("#display-company-Bandwidth"); +displayResources.text("Loading data from JSON source...");$.ajax({type: "GET",url: "https://api.iextrading.com/1.0/stock/BAND/company",success: function(result) {console.log(result);var output ="<table><thead><tr><th>symbol</th><th>companyName</th><th>exchange</th><th>industry</th><th>website</th><th>description</th><th>CEO</th><th>issuetype</th><th>sector</th><th>tags</th></thead><tbody>";output +="<tr><td>" +result.symbol+"</td><td>" +result.companyName+"</td><td>" +result.exchange +"</td><td>" +result.industry+"</td><td>" +result.website+"</td><td>" +result.description+"</td><td>" +result.CEO+"</td><td>" +result.issueType+"</td><td>" +result.sector+"</td></tr>";output += "</tbody></table>";displayResources.html(output);$("table").addClass("table");}});});


$("#retrieve-company-BuckleInc").click(function() {var displayResources = $("#display-company-BuckleInc"); +displayResources.text("Loading data from JSON source...");$.ajax({type: "GET",url: "https://api.iextrading.com/1.0/stock/BKE/company",success: function(result) {console.log(result);var output ="<table><thead><tr><th>symbol</th><th>companyName</th><th>exchange</th><th>industry</th><th>website</th><th>description</th><th>CEO</th><th>issuetype</th><th>sector</th><th>tags</th></thead><tbody>";output +="<tr><td>" +result.symbol+"</td><td>" +result.companyName+"</td><td>" +result.exchange +"</td><td>" +result.industry+"</td><td>" +result.website+"</td><td>" +result.description+"</td><td>" +result.CEO+"</td><td>" +result.issueType+"</td><td>" +result.sector+"</td></tr>";output += "</tbody></table>";displayResources.html(output);$("table").addClass("table");}});});


$("#retrieve-company-BJsRestaurant").click(function() {var displayResources = $("#display-company-BJsRestaurant"); +displayResources.text("Loading data from JSON source...");$.ajax({type: "GET",url: "https://api.iextrading.com/1.0/stock/BJRI/company",success: function(result) {console.log(result);var output ="<table><thead><tr><th>symbol</th><th>companyName</th><th>exchange</th><th>industry</th><th>website</th><th>description</th><th>CEO</th><th>issuetype</th><th>sector</th><th>tags</th></thead><tbody>";output +="<tr><td>" +result.symbol+"</td><td>" +result.companyName+"</td><td>" +result.exchange +"</td><td>" +result.industry+"</td><td>" +result.website+"</td><td>" +result.description+"</td><td>" +result.CEO+"</td><td>" +result.issueType+"</td><td>" +result.sector+"</td></tr>";output += "</tbody></table>";displayResources.html(output);$("table").addClass("table");}});});


$("#retrieve-company-GibraltarIndustries").click(function() {var displayResources = $("#display-company-GibraltarIndustries"); +displayResources.text("Loading data from JSON source...");$.ajax({type: "GET",url: "https://api.iextrading.com/1.0/stock/ROCK/company",success: function(result) {console.log(result);var output ="<table><thead><tr><th>symbol</th><th>companyName</th><th>exchange</th><th>industry</th><th>website</th><th>description</th><th>CEO</th><th>issuetype</th><th>sector</th><th>tags</th></thead><tbody>";output +="<tr><td>" +result.symbol+"</td><td>" +result.companyName+"</td><td>" +result.exchange +"</td><td>" +result.industry+"</td><td>" +result.website+"</td><td>" +result.description+"</td><td>" +result.CEO+"</td><td>" +result.issueType+"</td><td>" +result.sector+"</td></tr>";output += "</tbody></table>";displayResources.html(output);$("table").addClass("table");}});});


$("#retrieve-company-MarcusandMillichapInc").click(function() {var displayResources = $("#display-company-MarcusandMillichapInc"); +displayResources.text("Loading data from JSON source...");$.ajax({type: "GET",url: "https://api.iextrading.com/1.0/stock/MMI/company",success: function(result) {console.log(result);var output ="<table><thead><tr><th>symbol</th><th>companyName</th><th>exchange</th><th>industry</th><th>website</th><th>description</th><th>CEO</th><th>issuetype</th><th>sector</th><th>tags</th></thead><tbody>";output +="<tr><td>" +result.symbol+"</td><td>" +result.companyName+"</td><td>" +result.exchange +"</td><td>" +result.industry+"</td><td>" +result.website+"</td><td>" +result.description+"</td><td>" +result.CEO+"</td><td>" +result.issueType+"</td><td>" +result.sector+"</td></tr>";output += "</tbody></table>";displayResources.html(output);$("table").addClass("table");}});});


$("#retrieve-company-AngiHomeServices").click(function() {var displayResources = $("#display-company-AngiHomeServices"); +displayResources.text("Loading data from JSON source...");$.ajax({type: "GET",url: "https://api.iextrading.com/1.0/stock/ANGI/company",success: function(result) {console.log(result);var output ="<table><thead><tr><th>symbol</th><th>companyName</th><th>exchange</th><th>industry</th><th>website</th><th>description</th><th>CEO</th><th>issuetype</th><th>sector</th><th>tags</th></thead><tbody>";output +="<tr><td>" +result.symbol+"</td><td>" +result.companyName+"</td><td>" +result.exchange +"</td><td>" +result.industry+"</td><td>" +result.website+"</td><td>" +result.description+"</td><td>" +result.CEO+"</td><td>" +result.issueType+"</td><td>" +result.sector+"</td></tr>";output += "</tbody></table>";displayResources.html(output);$("table").addClass("table");}});});


$("#retrieve-company-Nordstrom").click(function() {var displayResources = $("#display-company-Nordstrom"); +displayResources.text("Loading data from JSON source...");$.ajax({type: "GET",url: "https://api.iextrading.com/1.0/stock/JWN/company",success: function(result) {console.log(result);var output ="<table><thead><tr><th>symbol</th><th>companyName</th><th>exchange</th><th>industry</th><th>website</th><th>description</th><th>CEO</th><th>issuetype</th><th>sector</th><th>tags</th></thead><tbody>";output +="<tr><td>" +result.symbol+"</td><td>" +result.companyName+"</td><td>" +result.exchange +"</td><td>" +result.industry+"</td><td>" +result.website+"</td><td>" +result.description+"</td><td>" +result.CEO+"</td><td>" +result.issueType+"</td><td>" +result.sector+"</td></tr>";output += "</tbody></table>";displayResources.html(output);$("table").addClass("table");}});});


$("#retrieve-company-ColumbiaSportswear").click(function() {var displayResources = $("#display-company-ColumbiaSportswear"); +displayResources.text("Loading data from JSON source...");$.ajax({type: "GET",url: "https://api.iextrading.com/1.0/stock/COLM/company",success: function(result) {console.log(result);var output ="<table><thead><tr><th>symbol</th><th>companyName</th><th>exchange</th><th>industry</th><th>website</th><th>description</th><th>CEO</th><th>issuetype</th><th>sector</th><th>tags</th></thead><tbody>";output +="<tr><td>" +result.symbol+"</td><td>" +result.companyName+"</td><td>" +result.exchange +"</td><td>" +result.industry+"</td><td>" +result.website+"</td><td>" +result.description+"</td><td>" +result.CEO+"</td><td>" +result.issueType+"</td><td>" +result.sector+"</td></tr>";output += "</tbody></table>";displayResources.html(output);$("table").addClass("table");}});});


$("#retrieve-company-JazzPharmaceuticals").click(function() {var displayResources = $("#display-company-JazzPharmaceuticals"); +displayResources.text("Loading data from JSON source...");$.ajax({type: "GET",url: "https://api.iextrading.com/1.0/stock/JAZZ/company",success: function(result) {console.log(result);var output ="<table><thead><tr><th>symbol</th><th>companyName</th><th>exchange</th><th>industry</th><th>website</th><th>description</th><th>CEO</th><th>issuetype</th><th>sector</th><th>tags</th></thead><tbody>";output +="<tr><td>" +result.symbol+"</td><td>" +result.companyName+"</td><td>" +result.exchange +"</td><td>" +result.industry+"</td><td>" +result.website+"</td><td>" +result.description+"</td><td>" +result.CEO+"</td><td>" +result.issueType+"</td><td>" +result.sector+"</td></tr>";output += "</tbody></table>";displayResources.html(output);$("table").addClass("table");}});});


$("#retrieve-company-BradyCorp").click(function() {var displayResources = $("#display-company-BradyCorp"); +displayResources.text("Loading data from JSON source...");$.ajax({type: "GET",url: "https://api.iextrading.com/1.0/stock/BRC/company",success: function(result) {console.log(result);var output ="<table><thead><tr><th>symbol</th><th>companyName</th><th>exchange</th><th>industry</th><th>website</th><th>description</th><th>CEO</th><th>issuetype</th><th>sector</th><th>tags</th></thead><tbody>";output +="<tr><td>" +result.symbol+"</td><td>" +result.companyName+"</td><td>" +result.exchange +"</td><td>" +result.industry+"</td><td>" +result.website+"</td><td>" +result.description+"</td><td>" +result.CEO+"</td><td>" +result.issueType+"</td><td>" +result.sector+"</td></tr>";output += "</tbody></table>";displayResources.html(output);$("table").addClass("table");}});});
});
