$(document).ready(function () {
  $("#retrieve-earnings-Walmart").click(function()
  {var displayResources = $("#display-earnings-Walmart");
  +displayResources.text("Loading data from JSON source...");
   $.getJSON("https://api.iextrading.com/1.0/stock/wmt/earnings", function (data) {
var mdata ="<table><thead><tr><th>symbol</th><th>EPSReportDate</th><th>fiscalPeriod</th><th>fiscalEndDate</th><th>actualEPS</th><th>consensusEPS</th><th>estimatedEPS</th><th>numberOfEstimates</th><th>EPSSurpriseDollar</th><th>yearAgo</th><th>yearAgoChangePercent</th><th>estimatedChangePercent</th></thead><tbody>";

       $.each(data['earnings'], function (key, value) {

           mdata += '<tr>';
           mdata += '<td>'+data.symbol + '</td>';
           mdata += '<td>'+value.EPSReportDate + '</td>';
           mdata += '<td>'+value.fiscalPeriod + '</td>';
           mdata += '<td>'+value.fiscalEndDate + '</td>';
           mdata += '<td>'+value.actualEPS + '</td>';
           mdata += '<td>'+value.consensusEPS + '</td>';
           mdata += '<td>'+value.estimatedEPS + '</td>';
           mdata += '<td>'+value.numberOfEstimates + '</td>';
           mdata += '<td>'+value.EPSSurpriseDollar + '</td>';
           mdata += '<td>'+value.yearAgo + '</td>';
           mdata += '<td>'+value.yearAgoChangePercent + '</td>';
           mdata += '<td>'+value.estimatedChangePercent + '</td>';
           mdata += '</tr>';
       });
       mdata += "</tbody></table>";
       displayResources.html(mdata);
       $("table").addClass("table");
   });
});
$("#retrieve-earnings-UnitedHealth").click(function() {var displayResources = $("#display-earnings-UnitedHealth");+displayResources.text("Loading data from JSON source...");$.getJSON("https://api.iextrading.com/1.0/stock/UNH/earnings", function (data) {var mdata ="<table><thead><tr><th>symbol</th><th>EPSReportDate</th><th>fiscalPeriod</th><th>fiscalEndDate</th><th>actualEPS</th><th>consensusEPS</th><th>estimatedEPS</th><th>numberOfEstimates</th><th>EPSSurpriseDollar</th><th>yearAgo</th><th>yearAgoChangePercent</th><th>estimatedChangePercent</th></thead><tbody>";$.each(data['earnings'], function (key, value) {mdata += '<tr>';mdata += '<td>'+data.symbol + '</td>';mdata += '<td>'+value.EPSReportDate + '</td>';mdata += '<td>'+value.fiscalPeriod + '</td>';mdata += '<td>'+value.fiscalEndDate + '</td>';mdata += '<td>'+value.actualEPS + '</td>';mdata += '<td>'+value.consensusEPS + '</td>';mdata += '<td>'+value.estimatedEPS + '</td>';mdata += '<td>'+value.numberOfEstimates + '</td>';mdata += '<td>'+value.EPSSurpriseDollar + '</td>';mdata += '<td>'+value.yearAgo + '</td>';mdata += '<td>'+value.yearAgoChangePercent + '</td>';mdata += '<td>'+value.estimatedChangePercent + '</td>';mdata += '</tr>';});mdata += "</tbody></table>";displayResources.html(mdata);$("table").addClass("table");});});


$("#retrieve-earnings-Apple").click(function() {var displayResources = $("#display-earnings-Apple");+displayResources.text("Loading data from JSON source...");$.getJSON("https://api.iextrading.com/1.0/stock/AAPL/earnings", function (data) {var mdata ="<table><thead><tr><th>symbol</th><th>EPSReportDate</th><th>fiscalPeriod</th><th>fiscalEndDate</th><th>actualEPS</th><th>consensusEPS</th><th>estimatedEPS</th><th>numberOfEstimates</th><th>EPSSurpriseDollar</th><th>yearAgo</th><th>yearAgoChangePercent</th><th>estimatedChangePercent</th></thead><tbody>";$.each(data['earnings'], function (key, value) {mdata += '<tr>';mdata += '<td>'+data.symbol + '</td>';mdata += '<td>'+value.EPSReportDate + '</td>';mdata += '<td>'+value.fiscalPeriod + '</td>';mdata += '<td>'+value.fiscalEndDate + '</td>';mdata += '<td>'+value.actualEPS + '</td>';mdata += '<td>'+value.consensusEPS + '</td>';mdata += '<td>'+value.estimatedEPS + '</td>';mdata += '<td>'+value.numberOfEstimates + '</td>';mdata += '<td>'+value.EPSSurpriseDollar + '</td>';mdata += '<td>'+value.yearAgo + '</td>';mdata += '<td>'+value.yearAgoChangePercent + '</td>';mdata += '<td>'+value.estimatedChangePercent + '</td>';mdata += '</tr>';});mdata += "</tbody></table>";displayResources.html(mdata);$("table").addClass("table");});});


$("#retrieve-earnings-Mastercard").click(function() {var displayResources = $("#display-earnings-Mastercard");+displayResources.text("Loading data from JSON source...");$.getJSON("https://api.iextrading.com/1.0/stock/MA/earnings", function (data) {var mdata ="<table><thead><tr><th>symbol</th><th>EPSReportDate</th><th>fiscalPeriod</th><th>fiscalEndDate</th><th>actualEPS</th><th>consensusEPS</th><th>estimatedEPS</th><th>numberOfEstimates</th><th>EPSSurpriseDollar</th><th>yearAgo</th><th>yearAgoChangePercent</th><th>estimatedChangePercent</th></thead><tbody>";$.each(data['earnings'], function (key, value) {mdata += '<tr>';mdata += '<td>'+data.symbol + '</td>';mdata += '<td>'+value.EPSReportDate + '</td>';mdata += '<td>'+value.fiscalPeriod + '</td>';mdata += '<td>'+value.fiscalEndDate + '</td>';mdata += '<td>'+value.actualEPS + '</td>';mdata += '<td>'+value.consensusEPS + '</td>';mdata += '<td>'+value.estimatedEPS + '</td>';mdata += '<td>'+value.numberOfEstimates + '</td>';mdata += '<td>'+value.EPSSurpriseDollar + '</td>';mdata += '<td>'+value.yearAgo + '</td>';mdata += '<td>'+value.yearAgoChangePercent + '</td>';mdata += '<td>'+value.estimatedChangePercent + '</td>';mdata += '</tr>';});mdata += "</tbody></table>";displayResources.html(mdata);$("table").addClass("table");});});


$("#retrieve-earnings-LululemonAthletica").click(function() {var displayResources = $("#display-earnings-LululemonAthletica");+displayResources.text("Loading data from JSON source...");$.getJSON("https://api.iextrading.com/1.0/stock/LULU/earnings", function (data) {var mdata ="<table><thead><tr><th>symbol</th><th>EPSReportDate</th><th>fiscalPeriod</th><th>fiscalEndDate</th><th>actualEPS</th><th>consensusEPS</th><th>estimatedEPS</th><th>numberOfEstimates</th><th>EPSSurpriseDollar</th><th>yearAgo</th><th>yearAgoChangePercent</th><th>estimatedChangePercent</th></thead><tbody>";$.each(data['earnings'], function (key, value) {mdata += '<tr>';mdata += '<td>'+data.symbol + '</td>';mdata += '<td>'+value.EPSReportDate + '</td>';mdata += '<td>'+value.fiscalPeriod + '</td>';mdata += '<td>'+value.fiscalEndDate + '</td>';mdata += '<td>'+value.actualEPS + '</td>';mdata += '<td>'+value.consensusEPS + '</td>';mdata += '<td>'+value.estimatedEPS + '</td>';mdata += '<td>'+value.numberOfEstimates + '</td>';mdata += '<td>'+value.EPSSurpriseDollar + '</td>';mdata += '<td>'+value.yearAgo + '</td>';mdata += '<td>'+value.yearAgoChangePercent + '</td>';mdata += '<td>'+value.estimatedChangePercent + '</td>';mdata += '</tr>';});mdata += "</tbody></table>";displayResources.html(mdata);$("table").addClass("table");});});


$("#retrieve-earnings-BestBuy").click(function() {var displayResources = $("#display-earnings-BestBuy");+displayResources.text("Loading data from JSON source...");$.getJSON("https://api.iextrading.com/1.0/stock/BBY/earnings", function (data) {var mdata ="<table><thead><tr><th>symbol</th><th>EPSReportDate</th><th>fiscalPeriod</th><th>fiscalEndDate</th><th>actualEPS</th><th>consensusEPS</th><th>estimatedEPS</th><th>numberOfEstimates</th><th>EPSSurpriseDollar</th><th>yearAgo</th><th>yearAgoChangePercent</th><th>estimatedChangePercent</th></thead><tbody>";$.each(data['earnings'], function (key, value) {mdata += '<tr>';mdata += '<td>'+data.symbol + '</td>';mdata += '<td>'+value.EPSReportDate + '</td>';mdata += '<td>'+value.fiscalPeriod + '</td>';mdata += '<td>'+value.fiscalEndDate + '</td>';mdata += '<td>'+value.actualEPS + '</td>';mdata += '<td>'+value.consensusEPS + '</td>';mdata += '<td>'+value.estimatedEPS + '</td>';mdata += '<td>'+value.numberOfEstimates + '</td>';mdata += '<td>'+value.EPSSurpriseDollar + '</td>';mdata += '<td>'+value.yearAgo + '</td>';mdata += '<td>'+value.yearAgoChangePercent + '</td>';mdata += '<td>'+value.estimatedChangePercent + '</td>';mdata += '</tr>';});mdata += "</tbody></table>";displayResources.html(mdata);$("table").addClass("table");});});


$("#retrieve-earnings-Yum").click(function() {var displayResources = $("#display-earnings-Yum");+displayResources.text("Loading data from JSON source...");$.getJSON("https://api.iextrading.com/1.0/stock/YUM/earnings", function (data) {var mdata ="<table><thead><tr><th>symbol</th><th>EPSReportDate</th><th>fiscalPeriod</th><th>fiscalEndDate</th><th>actualEPS</th><th>consensusEPS</th><th>estimatedEPS</th><th>numberOfEstimates</th><th>EPSSurpriseDollar</th><th>yearAgo</th><th>yearAgoChangePercent</th><th>estimatedChangePercent</th></thead><tbody>";$.each(data['earnings'], function (key, value) {mdata += '<tr>';mdata += '<td>'+data.symbol + '</td>';mdata += '<td>'+value.EPSReportDate + '</td>';mdata += '<td>'+value.fiscalPeriod + '</td>';mdata += '<td>'+value.fiscalEndDate + '</td>';mdata += '<td>'+value.actualEPS + '</td>';mdata += '<td>'+value.consensusEPS + '</td>';mdata += '<td>'+value.estimatedEPS + '</td>';mdata += '<td>'+value.numberOfEstimates + '</td>';mdata += '<td>'+value.EPSSurpriseDollar + '</td>';mdata += '<td>'+value.yearAgo + '</td>';mdata += '<td>'+value.yearAgoChangePercent + '</td>';mdata += '<td>'+value.estimatedChangePercent + '</td>';mdata += '</tr>';});mdata += "</tbody></table>";displayResources.html(mdata);$("table").addClass("table");});});


$("#retrieve-earnings-TJX").click(function() {var displayResources = $("#display-earnings-TJX");+displayResources.text("Loading data from JSON source...");$.getJSON("https://api.iextrading.com/1.0/stock/TJX/earnings", function (data) {var mdata ="<table><thead><tr><th>symbol</th><th>EPSReportDate</th><th>fiscalPeriod</th><th>fiscalEndDate</th><th>actualEPS</th><th>consensusEPS</th><th>estimatedEPS</th><th>numberOfEstimates</th><th>EPSSurpriseDollar</th><th>yearAgo</th><th>yearAgoChangePercent</th><th>estimatedChangePercent</th></thead><tbody>";$.each(data['earnings'], function (key, value) {mdata += '<tr>';mdata += '<td>'+data.symbol + '</td>';mdata += '<td>'+value.EPSReportDate + '</td>';mdata += '<td>'+value.fiscalPeriod + '</td>';mdata += '<td>'+value.fiscalEndDate + '</td>';mdata += '<td>'+value.actualEPS + '</td>';mdata += '<td>'+value.consensusEPS + '</td>';mdata += '<td>'+value.estimatedEPS + '</td>';mdata += '<td>'+value.numberOfEstimates + '</td>';mdata += '<td>'+value.EPSSurpriseDollar + '</td>';mdata += '<td>'+value.yearAgo + '</td>';mdata += '<td>'+value.yearAgoChangePercent + '</td>';mdata += '<td>'+value.estimatedChangePercent + '</td>';mdata += '</tr>';});mdata += "</tbody></table>";displayResources.html(mdata);$("table").addClass("table");});});


$("#retrieve-earnings-Sony").click(function() {var displayResources = $("#display-earnings-Sony");+displayResources.text("Loading data from JSON source...");$.getJSON("https://api.iextrading.com/1.0/stock/SNE/earnings", function (data) {var mdata ="<table><thead><tr><th>symbol</th><th>EPSReportDate</th><th>fiscalPeriod</th><th>fiscalEndDate</th><th>actualEPS</th><th>consensusEPS</th><th>estimatedEPS</th><th>numberOfEstimates</th><th>EPSSurpriseDollar</th><th>yearAgo</th><th>yearAgoChangePercent</th><th>estimatedChangePercent</th></thead><tbody>";$.each(data['earnings'], function (key, value) {mdata += '<tr>';mdata += '<td>'+data.symbol + '</td>';mdata += '<td>'+value.EPSReportDate + '</td>';mdata += '<td>'+value.fiscalPeriod + '</td>';mdata += '<td>'+value.fiscalEndDate + '</td>';mdata += '<td>'+value.actualEPS + '</td>';mdata += '<td>'+value.consensusEPS + '</td>';mdata += '<td>'+value.estimatedEPS + '</td>';mdata += '<td>'+value.numberOfEstimates + '</td>';mdata += '<td>'+value.EPSSurpriseDollar + '</td>';mdata += '<td>'+value.yearAgo + '</td>';mdata += '<td>'+value.yearAgoChangePercent + '</td>';mdata += '<td>'+value.estimatedChangePercent + '</td>';mdata += '</tr>';});mdata += "</tbody></table>";displayResources.html(mdata);$("table").addClass("table");});});


$("#retrieve-earnings-Costco").click(function() {var displayResources = $("#display-earnings-Costco");+displayResources.text("Loading data from JSON source...");$.getJSON("https://api.iextrading.com/1.0/stock/COST/earnings", function (data) {var mdata ="<table><thead><tr><th>symbol</th><th>EPSReportDate</th><th>fiscalPeriod</th><th>fiscalEndDate</th><th>actualEPS</th><th>consensusEPS</th><th>estimatedEPS</th><th>numberOfEstimates</th><th>EPSSurpriseDollar</th><th>yearAgo</th><th>yearAgoChangePercent</th><th>estimatedChangePercent</th></thead><tbody>";$.each(data['earnings'], function (key, value) {mdata += '<tr>';mdata += '<td>'+data.symbol + '</td>';mdata += '<td>'+value.EPSReportDate + '</td>';mdata += '<td>'+value.fiscalPeriod + '</td>';mdata += '<td>'+value.fiscalEndDate + '</td>';mdata += '<td>'+value.actualEPS + '</td>';mdata += '<td>'+value.consensusEPS + '</td>';mdata += '<td>'+value.estimatedEPS + '</td>';mdata += '<td>'+value.numberOfEstimates + '</td>';mdata += '<td>'+value.EPSSurpriseDollar + '</td>';mdata += '<td>'+value.yearAgo + '</td>';mdata += '<td>'+value.yearAgoChangePercent + '</td>';mdata += '<td>'+value.estimatedChangePercent + '</td>';mdata += '</tr>';});mdata += "</tbody></table>";displayResources.html(mdata);$("table").addClass("table");});});


$("#retrieve-earnings-Conocophillips").click(function() {var displayResources = $("#display-earnings-Conocophillips");+displayResources.text("Loading data from JSON source...");$.getJSON("https://api.iextrading.com/1.0/stock/COP/earnings", function (data) {var mdata ="<table><thead><tr><th>symbol</th><th>EPSReportDate</th><th>fiscalPeriod</th><th>fiscalEndDate</th><th>actualEPS</th><th>consensusEPS</th><th>estimatedEPS</th><th>numberOfEstimates</th><th>EPSSurpriseDollar</th><th>yearAgo</th><th>yearAgoChangePercent</th><th>estimatedChangePercent</th></thead><tbody>";$.each(data['earnings'], function (key, value) {mdata += '<tr>';mdata += '<td>'+data.symbol + '</td>';mdata += '<td>'+value.EPSReportDate + '</td>';mdata += '<td>'+value.fiscalPeriod + '</td>';mdata += '<td>'+value.fiscalEndDate + '</td>';mdata += '<td>'+value.actualEPS + '</td>';mdata += '<td>'+value.consensusEPS + '</td>';mdata += '<td>'+value.estimatedEPS + '</td>';mdata += '<td>'+value.numberOfEstimates + '</td>';mdata += '<td>'+value.EPSSurpriseDollar + '</td>';mdata += '<td>'+value.yearAgo + '</td>';mdata += '<td>'+value.yearAgoChangePercent + '</td>';mdata += '<td>'+value.estimatedChangePercent + '</td>';mdata += '</tr>';});mdata += "</tbody></table>";displayResources.html(mdata);$("table").addClass("table");});});


$("#retrieve-earnings-SynchronyFinancial").click(function() {var displayResources = $("#display-earnings-SynchronyFinancial");+displayResources.text("Loading data from JSON source...");$.getJSON("https://api.iextrading.com/1.0/stock/SYF/earnings", function (data) {var mdata ="<table><thead><tr><th>symbol</th><th>EPSReportDate</th><th>fiscalPeriod</th><th>fiscalEndDate</th><th>actualEPS</th><th>consensusEPS</th><th>estimatedEPS</th><th>numberOfEstimates</th><th>EPSSurpriseDollar</th><th>yearAgo</th><th>yearAgoChangePercent</th><th>estimatedChangePercent</th></thead><tbody>";$.each(data['earnings'], function (key, value) {mdata += '<tr>';mdata += '<td>'+data.symbol + '</td>';mdata += '<td>'+value.EPSReportDate + '</td>';mdata += '<td>'+value.fiscalPeriod + '</td>';mdata += '<td>'+value.fiscalEndDate + '</td>';mdata += '<td>'+value.actualEPS + '</td>';mdata += '<td>'+value.consensusEPS + '</td>';mdata += '<td>'+value.estimatedEPS + '</td>';mdata += '<td>'+value.numberOfEstimates + '</td>';mdata += '<td>'+value.EPSSurpriseDollar + '</td>';mdata += '<td>'+value.yearAgo + '</td>';mdata += '<td>'+value.yearAgoChangePercent + '</td>';mdata += '<td>'+value.estimatedChangePercent + '</td>';mdata += '</tr>';});mdata += "</tbody></table>";displayResources.html(mdata);$("table").addClass("table");});});


$("#retrieve-earnings-CapitalOne").click(function() {var displayResources = $("#display-earnings-CapitalOne");+displayResources.text("Loading data from JSON source...");$.getJSON("https://api.iextrading.com/1.0/stock/COF/earnings", function (data) {var mdata ="<table><thead><tr><th>symbol</th><th>EPSReportDate</th><th>fiscalPeriod</th><th>fiscalEndDate</th><th>actualEPS</th><th>consensusEPS</th><th>estimatedEPS</th><th>numberOfEstimates</th><th>EPSSurpriseDollar</th><th>yearAgo</th><th>yearAgoChangePercent</th><th>estimatedChangePercent</th></thead><tbody>";$.each(data['earnings'], function (key, value) {mdata += '<tr>';mdata += '<td>'+data.symbol + '</td>';mdata += '<td>'+value.EPSReportDate + '</td>';mdata += '<td>'+value.fiscalPeriod + '</td>';mdata += '<td>'+value.fiscalEndDate + '</td>';mdata += '<td>'+value.actualEPS + '</td>';mdata += '<td>'+value.consensusEPS + '</td>';mdata += '<td>'+value.estimatedEPS + '</td>';mdata += '<td>'+value.numberOfEstimates + '</td>';mdata += '<td>'+value.EPSSurpriseDollar + '</td>';mdata += '<td>'+value.yearAgo + '</td>';mdata += '<td>'+value.yearAgoChangePercent + '</td>';mdata += '<td>'+value.estimatedChangePercent + '</td>';mdata += '</tr>';});mdata += "</tbody></table>";displayResources.html(mdata);$("table").addClass("table");});});


$("#retrieve-earnings-BankOfMontreal").click(function() {var displayResources = $("#display-earnings-BankOfMontreal");+displayResources.text("Loading data from JSON source...");$.getJSON("https://api.iextrading.com/1.0/stock/BMO/earnings", function (data) {var mdata ="<table><thead><tr><th>symbol</th><th>EPSReportDate</th><th>fiscalPeriod</th><th>fiscalEndDate</th><th>actualEPS</th><th>consensusEPS</th><th>estimatedEPS</th><th>numberOfEstimates</th><th>EPSSurpriseDollar</th><th>yearAgo</th><th>yearAgoChangePercent</th><th>estimatedChangePercent</th></thead><tbody>";$.each(data['earnings'], function (key, value) {mdata += '<tr>';mdata += '<td>'+data.symbol + '</td>';mdata += '<td>'+value.EPSReportDate + '</td>';mdata += '<td>'+value.fiscalPeriod + '</td>';mdata += '<td>'+value.fiscalEndDate + '</td>';mdata += '<td>'+value.actualEPS + '</td>';mdata += '<td>'+value.consensusEPS + '</td>';mdata += '<td>'+value.estimatedEPS + '</td>';mdata += '<td>'+value.numberOfEstimates + '</td>';mdata += '<td>'+value.EPSSurpriseDollar + '</td>';mdata += '<td>'+value.yearAgo + '</td>';mdata += '<td>'+value.yearAgoChangePercent + '</td>';mdata += '<td>'+value.estimatedChangePercent + '</td>';mdata += '</tr>';});mdata += "</tbody></table>";displayResources.html(mdata);$("table").addClass("table");});});


$("#retrieve-earnings-BristolMyers").click(function() {var displayResources = $("#display-earnings-BristolMyers");+displayResources.text("Loading data from JSON source...");$.getJSON("https://api.iextrading.com/1.0/stock/BMY/earnings", function (data) {var mdata ="<table><thead><tr><th>symbol</th><th>EPSReportDate</th><th>fiscalPeriod</th><th>fiscalEndDate</th><th>actualEPS</th><th>consensusEPS</th><th>estimatedEPS</th><th>numberOfEstimates</th><th>EPSSurpriseDollar</th><th>yearAgo</th><th>yearAgoChangePercent</th><th>estimatedChangePercent</th></thead><tbody>";$.each(data['earnings'], function (key, value) {mdata += '<tr>';mdata += '<td>'+data.symbol + '</td>';mdata += '<td>'+value.EPSReportDate + '</td>';mdata += '<td>'+value.fiscalPeriod + '</td>';mdata += '<td>'+value.fiscalEndDate + '</td>';mdata += '<td>'+value.actualEPS + '</td>';mdata += '<td>'+value.consensusEPS + '</td>';mdata += '<td>'+value.estimatedEPS + '</td>';mdata += '<td>'+value.numberOfEstimates + '</td>';mdata += '<td>'+value.EPSSurpriseDollar + '</td>';mdata += '<td>'+value.yearAgo + '</td>';mdata += '<td>'+value.yearAgoChangePercent + '</td>';mdata += '<td>'+value.estimatedChangePercent + '</td>';mdata += '</tr>';});mdata += "</tbody></table>";displayResources.html(mdata);$("table").addClass("table");});});


$("#retrieve-earnings-Raytheon").click(function() {var displayResources = $("#display-earnings-Raytheon");+displayResources.text("Loading data from JSON source...");$.getJSON("https://api.iextrading.com/1.0/stock/RTN/earnings", function (data) {var mdata ="<table><thead><tr><th>symbol</th><th>EPSReportDate</th><th>fiscalPeriod</th><th>fiscalEndDate</th><th>actualEPS</th><th>consensusEPS</th><th>estimatedEPS</th><th>numberOfEstimates</th><th>EPSSurpriseDollar</th><th>yearAgo</th><th>yearAgoChangePercent</th><th>estimatedChangePercent</th></thead><tbody>";$.each(data['earnings'], function (key, value) {mdata += '<tr>';mdata += '<td>'+data.symbol + '</td>';mdata += '<td>'+value.EPSReportDate + '</td>';mdata += '<td>'+value.fiscalPeriod + '</td>';mdata += '<td>'+value.fiscalEndDate + '</td>';mdata += '<td>'+value.actualEPS + '</td>';mdata += '<td>'+value.consensusEPS + '</td>';mdata += '<td>'+value.estimatedEPS + '</td>';mdata += '<td>'+value.numberOfEstimates + '</td>';mdata += '<td>'+value.EPSSurpriseDollar + '</td>';mdata += '<td>'+value.yearAgo + '</td>';mdata += '<td>'+value.yearAgoChangePercent + '</td>';mdata += '<td>'+value.estimatedChangePercent + '</td>';mdata += '</tr>';});mdata += "</tbody></table>";displayResources.html(mdata);$("table").addClass("table");});});


$("#retrieve-earnings-Dell").click(function() {var displayResources = $("#display-earnings-Dell");+displayResources.text("Loading data from JSON source...");$.getJSON("https://api.iextrading.com/1.0/stock/DVMT/earnings", function (data) {var mdata ="<table><thead><tr><th>symbol</th><th>EPSReportDate</th><th>fiscalPeriod</th><th>fiscalEndDate</th><th>actualEPS</th><th>consensusEPS</th><th>estimatedEPS</th><th>numberOfEstimates</th><th>EPSSurpriseDollar</th><th>yearAgo</th><th>yearAgoChangePercent</th><th>estimatedChangePercent</th></thead><tbody>";$.each(data['earnings'], function (key, value) {mdata += '<tr>';mdata += '<td>'+data.symbol + '</td>';mdata += '<td>'+value.EPSReportDate + '</td>';mdata += '<td>'+value.fiscalPeriod + '</td>';mdata += '<td>'+value.fiscalEndDate + '</td>';mdata += '<td>'+value.actualEPS + '</td>';mdata += '<td>'+value.consensusEPS + '</td>';mdata += '<td>'+value.estimatedEPS + '</td>';mdata += '<td>'+value.numberOfEstimates + '</td>';mdata += '<td>'+value.EPSSurpriseDollar + '</td>';mdata += '<td>'+value.yearAgo + '</td>';mdata += '<td>'+value.yearAgoChangePercent + '</td>';mdata += '<td>'+value.estimatedChangePercent + '</td>';mdata += '</tr>';});mdata += "</tbody></table>";displayResources.html(mdata);$("table").addClass("table");});});


$("#retrieve-earnings-HewlettPackard").click(function() {var displayResources = $("#display-earnings-HewlettPackard");+displayResources.text("Loading data from JSON source...");$.getJSON("https://api.iextrading.com/1.0/stock/HPE/earnings", function (data) {var mdata ="<table><thead><tr><th>symbol</th><th>EPSReportDate</th><th>fiscalPeriod</th><th>fiscalEndDate</th><th>actualEPS</th><th>consensusEPS</th><th>estimatedEPS</th><th>numberOfEstimates</th><th>EPSSurpriseDollar</th><th>yearAgo</th><th>yearAgoChangePercent</th><th>estimatedChangePercent</th></thead><tbody>";$.each(data['earnings'], function (key, value) {mdata += '<tr>';mdata += '<td>'+data.symbol + '</td>';mdata += '<td>'+value.EPSReportDate + '</td>';mdata += '<td>'+value.fiscalPeriod + '</td>';mdata += '<td>'+value.fiscalEndDate + '</td>';mdata += '<td>'+value.actualEPS + '</td>';mdata += '<td>'+value.consensusEPS + '</td>';mdata += '<td>'+value.estimatedEPS + '</td>';mdata += '<td>'+value.numberOfEstimates + '</td>';mdata += '<td>'+value.EPSSurpriseDollar + '</td>';mdata += '<td>'+value.yearAgo + '</td>';mdata += '<td>'+value.yearAgoChangePercent + '</td>';mdata += '<td>'+value.estimatedChangePercent + '</td>';mdata += '</tr>';});mdata += "</tbody></table>";displayResources.html(mdata);$("table").addClass("table");});});


$("#retrieve-earnings-HP").click(function() {var displayResources = $("#display-earnings-HP");+displayResources.text("Loading data from JSON source...");$.getJSON("https://api.iextrading.com/1.0/stock/HPQ/earnings", function (data) {var mdata ="<table><thead><tr><th>symbol</th><th>EPSReportDate</th><th>fiscalPeriod</th><th>fiscalEndDate</th><th>actualEPS</th><th>consensusEPS</th><th>estimatedEPS</th><th>numberOfEstimates</th><th>EPSSurpriseDollar</th><th>yearAgo</th><th>yearAgoChangePercent</th><th>estimatedChangePercent</th></thead><tbody>";$.each(data['earnings'], function (key, value) {mdata += '<tr>';mdata += '<td>'+data.symbol + '</td>';mdata += '<td>'+value.EPSReportDate + '</td>';mdata += '<td>'+value.fiscalPeriod + '</td>';mdata += '<td>'+value.fiscalEndDate + '</td>';mdata += '<td>'+value.actualEPS + '</td>';mdata += '<td>'+value.consensusEPS + '</td>';mdata += '<td>'+value.estimatedEPS + '</td>';mdata += '<td>'+value.numberOfEstimates + '</td>';mdata += '<td>'+value.EPSSurpriseDollar + '</td>';mdata += '<td>'+value.yearAgo + '</td>';mdata += '<td>'+value.yearAgoChangePercent + '</td>';mdata += '<td>'+value.estimatedChangePercent + '</td>';mdata += '</tr>';});mdata += "</tbody></table>";displayResources.html(mdata);$("table").addClass("table");});});


$("#retrieve-earnings-Intuit").click(function() {var displayResources = $("#display-earnings-Intuit");+displayResources.text("Loading data from JSON source...");$.getJSON("https://api.iextrading.com/1.0/stock/INTU/earnings", function (data) {var mdata ="<table><thead><tr><th>symbol</th><th>EPSReportDate</th><th>fiscalPeriod</th><th>fiscalEndDate</th><th>actualEPS</th><th>consensusEPS</th><th>estimatedEPS</th><th>numberOfEstimates</th><th>EPSSurpriseDollar</th><th>yearAgo</th><th>yearAgoChangePercent</th><th>estimatedChangePercent</th></thead><tbody>";$.each(data['earnings'], function (key, value) {mdata += '<tr>';mdata += '<td>'+data.symbol + '</td>';mdata += '<td>'+value.EPSReportDate + '</td>';mdata += '<td>'+value.fiscalPeriod + '</td>';mdata += '<td>'+value.fiscalEndDate + '</td>';mdata += '<td>'+value.actualEPS + '</td>';mdata += '<td>'+value.consensusEPS + '</td>';mdata += '<td>'+value.estimatedEPS + '</td>';mdata += '<td>'+value.numberOfEstimates + '</td>';mdata += '<td>'+value.EPSSurpriseDollar + '</td>';mdata += '<td>'+value.yearAgo + '</td>';mdata += '<td>'+value.yearAgoChangePercent + '</td>';mdata += '<td>'+value.estimatedChangePercent + '</td>';mdata += '</tr>';});mdata += "</tbody></table>";displayResources.html(mdata);$("table").addClass("table");});});


$("#retrieve-earnings-Bandwidth").click(function() {var displayResources = $("#display-earnings-Bandwidth");+displayResources.text("Loading data from JSON source...");$.getJSON("https://api.iextrading.com/1.0/stock/BAND/earnings", function (data) {var mdata ="<table><thead><tr><th>symbol</th><th>EPSReportDate</th><th>fiscalPeriod</th><th>fiscalEndDate</th><th>actualEPS</th><th>consensusEPS</th><th>estimatedEPS</th><th>numberOfEstimates</th><th>EPSSurpriseDollar</th><th>yearAgo</th><th>yearAgoChangePercent</th><th>estimatedChangePercent</th></thead><tbody>";$.each(data['earnings'], function (key, value) {mdata += '<tr>';mdata += '<td>'+data.symbol + '</td>';mdata += '<td>'+value.EPSReportDate + '</td>';mdata += '<td>'+value.fiscalPeriod + '</td>';mdata += '<td>'+value.fiscalEndDate + '</td>';mdata += '<td>'+value.actualEPS + '</td>';mdata += '<td>'+value.consensusEPS + '</td>';mdata += '<td>'+value.estimatedEPS + '</td>';mdata += '<td>'+value.numberOfEstimates + '</td>';mdata += '<td>'+value.EPSSurpriseDollar + '</td>';mdata += '<td>'+value.yearAgo + '</td>';mdata += '<td>'+value.yearAgoChangePercent + '</td>';mdata += '<td>'+value.estimatedChangePercent + '</td>';mdata += '</tr>';});mdata += "</tbody></table>";displayResources.html(mdata);$("table").addClass("table");});});


$("#retrieve-earnings-BuckleInc").click(function() {var displayResources = $("#display-earnings-BuckleInc");+displayResources.text("Loading data from JSON source...");$.getJSON("https://api.iextrading.com/1.0/stock/BKE/earnings", function (data) {var mdata ="<table><thead><tr><th>symbol</th><th>EPSReportDate</th><th>fiscalPeriod</th><th>fiscalEndDate</th><th>actualEPS</th><th>consensusEPS</th><th>estimatedEPS</th><th>numberOfEstimates</th><th>EPSSurpriseDollar</th><th>yearAgo</th><th>yearAgoChangePercent</th><th>estimatedChangePercent</th></thead><tbody>";$.each(data['earnings'], function (key, value) {mdata += '<tr>';mdata += '<td>'+data.symbol + '</td>';mdata += '<td>'+value.EPSReportDate + '</td>';mdata += '<td>'+value.fiscalPeriod + '</td>';mdata += '<td>'+value.fiscalEndDate + '</td>';mdata += '<td>'+value.actualEPS + '</td>';mdata += '<td>'+value.consensusEPS + '</td>';mdata += '<td>'+value.estimatedEPS + '</td>';mdata += '<td>'+value.numberOfEstimates + '</td>';mdata += '<td>'+value.EPSSurpriseDollar + '</td>';mdata += '<td>'+value.yearAgo + '</td>';mdata += '<td>'+value.yearAgoChangePercent + '</td>';mdata += '<td>'+value.estimatedChangePercent + '</td>';mdata += '</tr>';});mdata += "</tbody></table>";displayResources.html(mdata);$("table").addClass("table");});});


$("#retrieve-earnings-BJsRestaurant").click(function() {var displayResources = $("#display-earnings-BJsRestaurant");+displayResources.text("Loading data from JSON source...");$.getJSON("https://api.iextrading.com/1.0/stock/BJRI/earnings", function (data) {var mdata ="<table><thead><tr><th>symbol</th><th>EPSReportDate</th><th>fiscalPeriod</th><th>fiscalEndDate</th><th>actualEPS</th><th>consensusEPS</th><th>estimatedEPS</th><th>numberOfEstimates</th><th>EPSSurpriseDollar</th><th>yearAgo</th><th>yearAgoChangePercent</th><th>estimatedChangePercent</th></thead><tbody>";$.each(data['earnings'], function (key, value) {mdata += '<tr>';mdata += '<td>'+data.symbol + '</td>';mdata += '<td>'+value.EPSReportDate + '</td>';mdata += '<td>'+value.fiscalPeriod + '</td>';mdata += '<td>'+value.fiscalEndDate + '</td>';mdata += '<td>'+value.actualEPS + '</td>';mdata += '<td>'+value.consensusEPS + '</td>';mdata += '<td>'+value.estimatedEPS + '</td>';mdata += '<td>'+value.numberOfEstimates + '</td>';mdata += '<td>'+value.EPSSurpriseDollar + '</td>';mdata += '<td>'+value.yearAgo + '</td>';mdata += '<td>'+value.yearAgoChangePercent + '</td>';mdata += '<td>'+value.estimatedChangePercent + '</td>';mdata += '</tr>';});mdata += "</tbody></table>";displayResources.html(mdata);$("table").addClass("table");});});


$("#retrieve-earnings-GibraltarIndustries").click(function() {var displayResources = $("#display-earnings-GibraltarIndustries");+displayResources.text("Loading data from JSON source...");$.getJSON("https://api.iextrading.com/1.0/stock/ROCK/earnings", function (data) {var mdata ="<table><thead><tr><th>symbol</th><th>EPSReportDate</th><th>fiscalPeriod</th><th>fiscalEndDate</th><th>actualEPS</th><th>consensusEPS</th><th>estimatedEPS</th><th>numberOfEstimates</th><th>EPSSurpriseDollar</th><th>yearAgo</th><th>yearAgoChangePercent</th><th>estimatedChangePercent</th></thead><tbody>";$.each(data['earnings'], function (key, value) {mdata += '<tr>';mdata += '<td>'+data.symbol + '</td>';mdata += '<td>'+value.EPSReportDate + '</td>';mdata += '<td>'+value.fiscalPeriod + '</td>';mdata += '<td>'+value.fiscalEndDate + '</td>';mdata += '<td>'+value.actualEPS + '</td>';mdata += '<td>'+value.consensusEPS + '</td>';mdata += '<td>'+value.estimatedEPS + '</td>';mdata += '<td>'+value.numberOfEstimates + '</td>';mdata += '<td>'+value.EPSSurpriseDollar + '</td>';mdata += '<td>'+value.yearAgo + '</td>';mdata += '<td>'+value.yearAgoChangePercent + '</td>';mdata += '<td>'+value.estimatedChangePercent + '</td>';mdata += '</tr>';});mdata += "</tbody></table>";displayResources.html(mdata);$("table").addClass("table");});});


$("#retrieve-earnings-MarcusandMillichapInc").click(function() {var displayResources = $("#display-earnings-MarcusandMillichapInc");+displayResources.text("Loading data from JSON source...");$.getJSON("https://api.iextrading.com/1.0/stock/MMI/earnings", function (data) {var mdata ="<table><thead><tr><th>symbol</th><th>EPSReportDate</th><th>fiscalPeriod</th><th>fiscalEndDate</th><th>actualEPS</th><th>consensusEPS</th><th>estimatedEPS</th><th>numberOfEstimates</th><th>EPSSurpriseDollar</th><th>yearAgo</th><th>yearAgoChangePercent</th><th>estimatedChangePercent</th></thead><tbody>";$.each(data['earnings'], function (key, value) {mdata += '<tr>';mdata += '<td>'+data.symbol + '</td>';mdata += '<td>'+value.EPSReportDate + '</td>';mdata += '<td>'+value.fiscalPeriod + '</td>';mdata += '<td>'+value.fiscalEndDate + '</td>';mdata += '<td>'+value.actualEPS + '</td>';mdata += '<td>'+value.consensusEPS + '</td>';mdata += '<td>'+value.estimatedEPS + '</td>';mdata += '<td>'+value.numberOfEstimates + '</td>';mdata += '<td>'+value.EPSSurpriseDollar + '</td>';mdata += '<td>'+value.yearAgo + '</td>';mdata += '<td>'+value.yearAgoChangePercent + '</td>';mdata += '<td>'+value.estimatedChangePercent + '</td>';mdata += '</tr>';});mdata += "</tbody></table>";displayResources.html(mdata);$("table").addClass("table");});});


$("#retrieve-earnings-AngiHomeServices").click(function() {var displayResources = $("#display-earnings-AngiHomeServices");+displayResources.text("Loading data from JSON source...");$.getJSON("https://api.iextrading.com/1.0/stock/ANGI/earnings", function (data) {var mdata ="<table><thead><tr><th>symbol</th><th>EPSReportDate</th><th>fiscalPeriod</th><th>fiscalEndDate</th><th>actualEPS</th><th>consensusEPS</th><th>estimatedEPS</th><th>numberOfEstimates</th><th>EPSSurpriseDollar</th><th>yearAgo</th><th>yearAgoChangePercent</th><th>estimatedChangePercent</th></thead><tbody>";$.each(data['earnings'], function (key, value) {mdata += '<tr>';mdata += '<td>'+data.symbol + '</td>';mdata += '<td>'+value.EPSReportDate + '</td>';mdata += '<td>'+value.fiscalPeriod + '</td>';mdata += '<td>'+value.fiscalEndDate + '</td>';mdata += '<td>'+value.actualEPS + '</td>';mdata += '<td>'+value.consensusEPS + '</td>';mdata += '<td>'+value.estimatedEPS + '</td>';mdata += '<td>'+value.numberOfEstimates + '</td>';mdata += '<td>'+value.EPSSurpriseDollar + '</td>';mdata += '<td>'+value.yearAgo + '</td>';mdata += '<td>'+value.yearAgoChangePercent + '</td>';mdata += '<td>'+value.estimatedChangePercent + '</td>';mdata += '</tr>';});mdata += "</tbody></table>";displayResources.html(mdata);$("table").addClass("table");});});


$("#retrieve-earnings-Nordstrom").click(function() {var displayResources = $("#display-earnings-Nordstrom");+displayResources.text("Loading data from JSON source...");$.getJSON("https://api.iextrading.com/1.0/stock/JWN/earnings", function (data) {var mdata ="<table><thead><tr><th>symbol</th><th>EPSReportDate</th><th>fiscalPeriod</th><th>fiscalEndDate</th><th>actualEPS</th><th>consensusEPS</th><th>estimatedEPS</th><th>numberOfEstimates</th><th>EPSSurpriseDollar</th><th>yearAgo</th><th>yearAgoChangePercent</th><th>estimatedChangePercent</th></thead><tbody>";$.each(data['earnings'], function (key, value) {mdata += '<tr>';mdata += '<td>'+data.symbol + '</td>';mdata += '<td>'+value.EPSReportDate + '</td>';mdata += '<td>'+value.fiscalPeriod + '</td>';mdata += '<td>'+value.fiscalEndDate + '</td>';mdata += '<td>'+value.actualEPS + '</td>';mdata += '<td>'+value.consensusEPS + '</td>';mdata += '<td>'+value.estimatedEPS + '</td>';mdata += '<td>'+value.numberOfEstimates + '</td>';mdata += '<td>'+value.EPSSurpriseDollar + '</td>';mdata += '<td>'+value.yearAgo + '</td>';mdata += '<td>'+value.yearAgoChangePercent + '</td>';mdata += '<td>'+value.estimatedChangePercent + '</td>';mdata += '</tr>';});mdata += "</tbody></table>";displayResources.html(mdata);$("table").addClass("table");});});


$("#retrieve-earnings-ColumbiaSportswear").click(function() {var displayResources = $("#display-earnings-ColumbiaSportswear");+displayResources.text("Loading data from JSON source...");$.getJSON("https://api.iextrading.com/1.0/stock/COLM/earnings", function (data) {var mdata ="<table><thead><tr><th>symbol</th><th>EPSReportDate</th><th>fiscalPeriod</th><th>fiscalEndDate</th><th>actualEPS</th><th>consensusEPS</th><th>estimatedEPS</th><th>numberOfEstimates</th><th>EPSSurpriseDollar</th><th>yearAgo</th><th>yearAgoChangePercent</th><th>estimatedChangePercent</th></thead><tbody>";$.each(data['earnings'], function (key, value) {mdata += '<tr>';mdata += '<td>'+data.symbol + '</td>';mdata += '<td>'+value.EPSReportDate + '</td>';mdata += '<td>'+value.fiscalPeriod + '</td>';mdata += '<td>'+value.fiscalEndDate + '</td>';mdata += '<td>'+value.actualEPS + '</td>';mdata += '<td>'+value.consensusEPS + '</td>';mdata += '<td>'+value.estimatedEPS + '</td>';mdata += '<td>'+value.numberOfEstimates + '</td>';mdata += '<td>'+value.EPSSurpriseDollar + '</td>';mdata += '<td>'+value.yearAgo + '</td>';mdata += '<td>'+value.yearAgoChangePercent + '</td>';mdata += '<td>'+value.estimatedChangePercent + '</td>';mdata += '</tr>';});mdata += "</tbody></table>";displayResources.html(mdata);$("table").addClass("table");});});


$("#retrieve-earnings-JazzPharmaceuticals").click(function() {var displayResources = $("#display-earnings-JazzPharmaceuticals");+displayResources.text("Loading data from JSON source...");$.getJSON("https://api.iextrading.com/1.0/stock/JAZZ/earnings", function (data) {var mdata ="<table><thead><tr><th>symbol</th><th>EPSReportDate</th><th>fiscalPeriod</th><th>fiscalEndDate</th><th>actualEPS</th><th>consensusEPS</th><th>estimatedEPS</th><th>numberOfEstimates</th><th>EPSSurpriseDollar</th><th>yearAgo</th><th>yearAgoChangePercent</th><th>estimatedChangePercent</th></thead><tbody>";$.each(data['earnings'], function (key, value) {mdata += '<tr>';mdata += '<td>'+data.symbol + '</td>';mdata += '<td>'+value.EPSReportDate + '</td>';mdata += '<td>'+value.fiscalPeriod + '</td>';mdata += '<td>'+value.fiscalEndDate + '</td>';mdata += '<td>'+value.actualEPS + '</td>';mdata += '<td>'+value.consensusEPS + '</td>';mdata += '<td>'+value.estimatedEPS + '</td>';mdata += '<td>'+value.numberOfEstimates + '</td>';mdata += '<td>'+value.EPSSurpriseDollar + '</td>';mdata += '<td>'+value.yearAgo + '</td>';mdata += '<td>'+value.yearAgoChangePercent + '</td>';mdata += '<td>'+value.estimatedChangePercent + '</td>';mdata += '</tr>';});mdata += "</tbody></table>";displayResources.html(mdata);$("table").addClass("table");});});


$("#retrieve-earnings-BradyCorp").click(function() {var displayResources = $("#display-earnings-BradyCorp");+displayResources.text("Loading data from JSON source...");$.getJSON("https://api.iextrading.com/1.0/stock/BRC/earnings", function (data) {var mdata ="<table><thead><tr><th>symbol</th><th>EPSReportDate</th><th>fiscalPeriod</th><th>fiscalEndDate</th><th>actualEPS</th><th>consensusEPS</th><th>estimatedEPS</th><th>numberOfEstimates</th><th>EPSSurpriseDollar</th><th>yearAgo</th><th>yearAgoChangePercent</th><th>estimatedChangePercent</th></thead><tbody>";$.each(data['earnings'], function (key, value) {mdata += '<tr>';mdata += '<td>'+data.symbol + '</td>';mdata += '<td>'+value.EPSReportDate + '</td>';mdata += '<td>'+value.fiscalPeriod + '</td>';mdata += '<td>'+value.fiscalEndDate + '</td>';mdata += '<td>'+value.actualEPS + '</td>';mdata += '<td>'+value.consensusEPS + '</td>';mdata += '<td>'+value.estimatedEPS + '</td>';mdata += '<td>'+value.numberOfEstimates + '</td>';mdata += '<td>'+value.EPSSurpriseDollar + '</td>';mdata += '<td>'+value.yearAgo + '</td>';mdata += '<td>'+value.yearAgoChangePercent + '</td>';mdata += '<td>'+value.estimatedChangePercent + '</td>';mdata += '</tr>';});mdata += "</tbody></table>";displayResources.html(mdata);$("table").addClass("table");});});

});
