$(document).ready(function () {
  $("#retrieve-financials-Walmart").click(function()
  {var displayResources = $("#display-financials-Walmart");
  +displayResources.text("Loading data from JSON source...");
   $.getJSON("https://api.iextrading.com/1.0/stock/wmt/financials?period=annual", function (data) {
var mdata ="<table><thead><tr><th>symbol</th><th>reportDate</th><th>grossProfit</th><th>costOfRevenue</th><th>operatingRevenue</th><th>totalRevenue</th><th>operatingIncome</th><th>netIncome</th><th>researchAndDevelopment</th><th>operatingExpense</th><th>currentAssets</th><th>totalAssets</th><th>totalLiabilities</th><th>currentCash</th><th>currentDebt</th><th>totalCash</th><th>totalDebt</th><th>shareholderEquity</th><th>cashChange</th><th>cashFlow</th><th>operatingGainsLosses</th></thead><tbody>";
       $.each(data['financials'], function (key, value) {
           mdata += '<tr>';
           mdata += '<td>'+data.symbol + '</td>';
           mdata += '<td>'+value.reportDate + '</td>';
           mdata += '<td>'+value.grossProfit + '</td>';
           mdata += '<td>'+value.costOfRevenue + '</td>';
           mdata += '<td>'+value.operatingRevenue + '</td>';
           mdata += '<td>'+value.totalRevenue + '</td>';
           mdata += '<td>'+value.operatingIncome + '</td>';
           mdata += '<td>'+value.netIncome + '</td>';
           mdata += '<td>'+value.researchAndDevelopment + '</td>';
           mdata += '<td>'+value.operatingExpense + '</td>';
           mdata += '<td>'+value.currentAssets + '</td>';
           mdata += '<td>'+value.totalAssets + '</td>';
           mdata += '<td>'+value.totalLiabilities + '</td>';
           mdata += '<td>'+value.currentCash + '</td>';
           mdata += '<td>'+value.currentDebt + '</td>';
           mdata += '<td>'+value.totalCash + '</td>';
           mdata += '<td>'+value.totalDebt + '</td>';
           mdata += '<td>'+value.shareholderEquity + '</td>';
           mdata += '<td>'+value.cashChange + '</td>';
           mdata += '<td>'+value.cashFlow + '</td>';
           mdata += '<td>'+value.operatingGainsLosses + '</td>';
           mdata += '</tr>';
       });
       mdata += "</tbody></table>";
       displayResources.html(mdata);
       $("table").addClass("table");
   });
});



$("#retrieve-financials-UnitedHealth").click(function(){var displayResources = $("#display-financials-UnitedHealth");+displayResources.text("Loading data from JSON source...");$.getJSON("https://api.iextrading.com/1.0/stock/UNH/financials?period=annual", function (data) {var mdata ="<table><thead><tr><th>symbol</th><th>reportDate</th><th>grossProfit</th><th>costOfRevenue</th><th>operatingRevenue</th><th>totalRevenue</th><th>operatingIncome</th><th>netIncome</th><th>researchAndDevelopment</th><th>operatingExpense</th><th>currentAssets</th><th>totalAssets</th><th>totalLiabilities</th><th>currentCash</th><th>currentDebt</th><th>totalCash</th><th>totalDebt</th><th>shareholderEquity</th><th>cashChange</th><th>cashFlow</th><th>operatingGainsLosses</th></thead><tbody>";$.each(data['financials'], function (key, value) {mdata += '<tr>';mdata += '<td>'+data.symbol + '</td>';mdata += '<td>'+value.reportDate + '</td>';mdata += '<td>'+value.grossProfit + '</td>';mdata += '<td>'+value.costOfRevenue + '</td>';mdata += '<td>'+value.operatingRevenue + '</td>';mdata += '<td>'+value.totalRevenue + '</td>';mdata += '<td>'+value.operatingIncome + '</td>';mdata += '<td>'+value.netIncome + '</td>';mdata += '<td>'+value.researchAndDevelopment + '</td>';mdata += '<td>'+value.operatingExpense + '</td>';mdata += '<td>'+value.currentAssets + '</td>';mdata += '<td>'+value.totalAssets + '</td>';mdata += '<td>'+value.totalLiabilities + '</td>';mdata += '<td>'+value.currentCash + '</td>';mdata += '<td>'+value.currentDebt + '</td>';mdata += '<td>'+value.totalCash + '</td>';mdata += '<td>'+value.totalDebt + '</td>';mdata += '<td>'+value.shareholderEquity + '</td>';mdata += '<td>'+value.cashChange + '</td>';mdata += '<td>'+value.cashFlow + '</td>';mdata += '<td>'+value.operatingGainsLosses + '</td>';mdata += '</tr>';});mdata += "</tbody></table>";displayResources.html(mdata);$("table").addClass("table");});});


$("#retrieve-financials-Apple").click(function(){var displayResources = $("#display-financials-Apple");+displayResources.text("Loading data from JSON source...");$.getJSON("https://api.iextrading.com/1.0/stock/AAPL/financials?period=annual", function (data) {var mdata ="<table><thead><tr><th>symbol</th><th>reportDate</th><th>grossProfit</th><th>costOfRevenue</th><th>operatingRevenue</th><th>totalRevenue</th><th>operatingIncome</th><th>netIncome</th><th>researchAndDevelopment</th><th>operatingExpense</th><th>currentAssets</th><th>totalAssets</th><th>totalLiabilities</th><th>currentCash</th><th>currentDebt</th><th>totalCash</th><th>totalDebt</th><th>shareholderEquity</th><th>cashChange</th><th>cashFlow</th><th>operatingGainsLosses</th></thead><tbody>";$.each(data['financials'], function (key, value) {mdata += '<tr>';mdata += '<td>'+data.symbol + '</td>';mdata += '<td>'+value.reportDate + '</td>';mdata += '<td>'+value.grossProfit + '</td>';mdata += '<td>'+value.costOfRevenue + '</td>';mdata += '<td>'+value.operatingRevenue + '</td>';mdata += '<td>'+value.totalRevenue + '</td>';mdata += '<td>'+value.operatingIncome + '</td>';mdata += '<td>'+value.netIncome + '</td>';mdata += '<td>'+value.researchAndDevelopment + '</td>';mdata += '<td>'+value.operatingExpense + '</td>';mdata += '<td>'+value.currentAssets + '</td>';mdata += '<td>'+value.totalAssets + '</td>';mdata += '<td>'+value.totalLiabilities + '</td>';mdata += '<td>'+value.currentCash + '</td>';mdata += '<td>'+value.currentDebt + '</td>';mdata += '<td>'+value.totalCash + '</td>';mdata += '<td>'+value.totalDebt + '</td>';mdata += '<td>'+value.shareholderEquity + '</td>';mdata += '<td>'+value.cashChange + '</td>';mdata += '<td>'+value.cashFlow + '</td>';mdata += '<td>'+value.operatingGainsLosses + '</td>';mdata += '</tr>';});mdata += "</tbody></table>";displayResources.html(mdata);$("table").addClass("table");});});


$("#retrieve-financials-Mastercard").click(function(){var displayResources = $("#display-financials-Mastercard");+displayResources.text("Loading data from JSON source...");$.getJSON("https://api.iextrading.com/1.0/stock/MA/financials?period=annual", function (data) {var mdata ="<table><thead><tr><th>symbol</th><th>reportDate</th><th>grossProfit</th><th>costOfRevenue</th><th>operatingRevenue</th><th>totalRevenue</th><th>operatingIncome</th><th>netIncome</th><th>researchAndDevelopment</th><th>operatingExpense</th><th>currentAssets</th><th>totalAssets</th><th>totalLiabilities</th><th>currentCash</th><th>currentDebt</th><th>totalCash</th><th>totalDebt</th><th>shareholderEquity</th><th>cashChange</th><th>cashFlow</th><th>operatingGainsLosses</th></thead><tbody>";$.each(data['financials'], function (key, value) {mdata += '<tr>';mdata += '<td>'+data.symbol + '</td>';mdata += '<td>'+value.reportDate + '</td>';mdata += '<td>'+value.grossProfit + '</td>';mdata += '<td>'+value.costOfRevenue + '</td>';mdata += '<td>'+value.operatingRevenue + '</td>';mdata += '<td>'+value.totalRevenue + '</td>';mdata += '<td>'+value.operatingIncome + '</td>';mdata += '<td>'+value.netIncome + '</td>';mdata += '<td>'+value.researchAndDevelopment + '</td>';mdata += '<td>'+value.operatingExpense + '</td>';mdata += '<td>'+value.currentAssets + '</td>';mdata += '<td>'+value.totalAssets + '</td>';mdata += '<td>'+value.totalLiabilities + '</td>';mdata += '<td>'+value.currentCash + '</td>';mdata += '<td>'+value.currentDebt + '</td>';mdata += '<td>'+value.totalCash + '</td>';mdata += '<td>'+value.totalDebt + '</td>';mdata += '<td>'+value.shareholderEquity + '</td>';mdata += '<td>'+value.cashChange + '</td>';mdata += '<td>'+value.cashFlow + '</td>';mdata += '<td>'+value.operatingGainsLosses + '</td>';mdata += '</tr>';});mdata += "</tbody></table>";displayResources.html(mdata);$("table").addClass("table");});});


$("#retrieve-financials-LululemonAthletica").click(function(){var displayResources = $("#display-financials-LululemonAthletica");+displayResources.text("Loading data from JSON source...");$.getJSON("https://api.iextrading.com/1.0/stock/LULU/financials?period=annual", function (data) {var mdata ="<table><thead><tr><th>symbol</th><th>reportDate</th><th>grossProfit</th><th>costOfRevenue</th><th>operatingRevenue</th><th>totalRevenue</th><th>operatingIncome</th><th>netIncome</th><th>researchAndDevelopment</th><th>operatingExpense</th><th>currentAssets</th><th>totalAssets</th><th>totalLiabilities</th><th>currentCash</th><th>currentDebt</th><th>totalCash</th><th>totalDebt</th><th>shareholderEquity</th><th>cashChange</th><th>cashFlow</th><th>operatingGainsLosses</th></thead><tbody>";$.each(data['financials'], function (key, value) {mdata += '<tr>';mdata += '<td>'+data.symbol + '</td>';mdata += '<td>'+value.reportDate + '</td>';mdata += '<td>'+value.grossProfit + '</td>';mdata += '<td>'+value.costOfRevenue + '</td>';mdata += '<td>'+value.operatingRevenue + '</td>';mdata += '<td>'+value.totalRevenue + '</td>';mdata += '<td>'+value.operatingIncome + '</td>';mdata += '<td>'+value.netIncome + '</td>';mdata += '<td>'+value.researchAndDevelopment + '</td>';mdata += '<td>'+value.operatingExpense + '</td>';mdata += '<td>'+value.currentAssets + '</td>';mdata += '<td>'+value.totalAssets + '</td>';mdata += '<td>'+value.totalLiabilities + '</td>';mdata += '<td>'+value.currentCash + '</td>';mdata += '<td>'+value.currentDebt + '</td>';mdata += '<td>'+value.totalCash + '</td>';mdata += '<td>'+value.totalDebt + '</td>';mdata += '<td>'+value.shareholderEquity + '</td>';mdata += '<td>'+value.cashChange + '</td>';mdata += '<td>'+value.cashFlow + '</td>';mdata += '<td>'+value.operatingGainsLosses + '</td>';mdata += '</tr>';});mdata += "</tbody></table>";displayResources.html(mdata);$("table").addClass("table");});});


$("#retrieve-financials-BestBuy").click(function(){var displayResources = $("#display-financials-BestBuy");+displayResources.text("Loading data from JSON source...");$.getJSON("https://api.iextrading.com/1.0/stock/BBY/financials?period=annual", function (data) {var mdata ="<table><thead><tr><th>symbol</th><th>reportDate</th><th>grossProfit</th><th>costOfRevenue</th><th>operatingRevenue</th><th>totalRevenue</th><th>operatingIncome</th><th>netIncome</th><th>researchAndDevelopment</th><th>operatingExpense</th><th>currentAssets</th><th>totalAssets</th><th>totalLiabilities</th><th>currentCash</th><th>currentDebt</th><th>totalCash</th><th>totalDebt</th><th>shareholderEquity</th><th>cashChange</th><th>cashFlow</th><th>operatingGainsLosses</th></thead><tbody>";$.each(data['financials'], function (key, value) {mdata += '<tr>';mdata += '<td>'+data.symbol + '</td>';mdata += '<td>'+value.reportDate + '</td>';mdata += '<td>'+value.grossProfit + '</td>';mdata += '<td>'+value.costOfRevenue + '</td>';mdata += '<td>'+value.operatingRevenue + '</td>';mdata += '<td>'+value.totalRevenue + '</td>';mdata += '<td>'+value.operatingIncome + '</td>';mdata += '<td>'+value.netIncome + '</td>';mdata += '<td>'+value.researchAndDevelopment + '</td>';mdata += '<td>'+value.operatingExpense + '</td>';mdata += '<td>'+value.currentAssets + '</td>';mdata += '<td>'+value.totalAssets + '</td>';mdata += '<td>'+value.totalLiabilities + '</td>';mdata += '<td>'+value.currentCash + '</td>';mdata += '<td>'+value.currentDebt + '</td>';mdata += '<td>'+value.totalCash + '</td>';mdata += '<td>'+value.totalDebt + '</td>';mdata += '<td>'+value.shareholderEquity + '</td>';mdata += '<td>'+value.cashChange + '</td>';mdata += '<td>'+value.cashFlow + '</td>';mdata += '<td>'+value.operatingGainsLosses + '</td>';mdata += '</tr>';});mdata += "</tbody></table>";displayResources.html(mdata);$("table").addClass("table");});});


$("#retrieve-financials-Yum").click(function(){var displayResources = $("#display-financials-Yum");+displayResources.text("Loading data from JSON source...");$.getJSON("https://api.iextrading.com/1.0/stock/YUM/financials?period=annual", function (data) {var mdata ="<table><thead><tr><th>symbol</th><th>reportDate</th><th>grossProfit</th><th>costOfRevenue</th><th>operatingRevenue</th><th>totalRevenue</th><th>operatingIncome</th><th>netIncome</th><th>researchAndDevelopment</th><th>operatingExpense</th><th>currentAssets</th><th>totalAssets</th><th>totalLiabilities</th><th>currentCash</th><th>currentDebt</th><th>totalCash</th><th>totalDebt</th><th>shareholderEquity</th><th>cashChange</th><th>cashFlow</th><th>operatingGainsLosses</th></thead><tbody>";$.each(data['financials'], function (key, value) {mdata += '<tr>';mdata += '<td>'+data.symbol + '</td>';mdata += '<td>'+value.reportDate + '</td>';mdata += '<td>'+value.grossProfit + '</td>';mdata += '<td>'+value.costOfRevenue + '</td>';mdata += '<td>'+value.operatingRevenue + '</td>';mdata += '<td>'+value.totalRevenue + '</td>';mdata += '<td>'+value.operatingIncome + '</td>';mdata += '<td>'+value.netIncome + '</td>';mdata += '<td>'+value.researchAndDevelopment + '</td>';mdata += '<td>'+value.operatingExpense + '</td>';mdata += '<td>'+value.currentAssets + '</td>';mdata += '<td>'+value.totalAssets + '</td>';mdata += '<td>'+value.totalLiabilities + '</td>';mdata += '<td>'+value.currentCash + '</td>';mdata += '<td>'+value.currentDebt + '</td>';mdata += '<td>'+value.totalCash + '</td>';mdata += '<td>'+value.totalDebt + '</td>';mdata += '<td>'+value.shareholderEquity + '</td>';mdata += '<td>'+value.cashChange + '</td>';mdata += '<td>'+value.cashFlow + '</td>';mdata += '<td>'+value.operatingGainsLosses + '</td>';mdata += '</tr>';});mdata += "</tbody></table>";displayResources.html(mdata);$("table").addClass("table");});});


$("#retrieve-financials-TJX").click(function(){var displayResources = $("#display-financials-TJX");+displayResources.text("Loading data from JSON source...");$.getJSON("https://api.iextrading.com/1.0/stock/TJX/financials?period=annual", function (data) {var mdata ="<table><thead><tr><th>symbol</th><th>reportDate</th><th>grossProfit</th><th>costOfRevenue</th><th>operatingRevenue</th><th>totalRevenue</th><th>operatingIncome</th><th>netIncome</th><th>researchAndDevelopment</th><th>operatingExpense</th><th>currentAssets</th><th>totalAssets</th><th>totalLiabilities</th><th>currentCash</th><th>currentDebt</th><th>totalCash</th><th>totalDebt</th><th>shareholderEquity</th><th>cashChange</th><th>cashFlow</th><th>operatingGainsLosses</th></thead><tbody>";$.each(data['financials'], function (key, value) {mdata += '<tr>';mdata += '<td>'+data.symbol + '</td>';mdata += '<td>'+value.reportDate + '</td>';mdata += '<td>'+value.grossProfit + '</td>';mdata += '<td>'+value.costOfRevenue + '</td>';mdata += '<td>'+value.operatingRevenue + '</td>';mdata += '<td>'+value.totalRevenue + '</td>';mdata += '<td>'+value.operatingIncome + '</td>';mdata += '<td>'+value.netIncome + '</td>';mdata += '<td>'+value.researchAndDevelopment + '</td>';mdata += '<td>'+value.operatingExpense + '</td>';mdata += '<td>'+value.currentAssets + '</td>';mdata += '<td>'+value.totalAssets + '</td>';mdata += '<td>'+value.totalLiabilities + '</td>';mdata += '<td>'+value.currentCash + '</td>';mdata += '<td>'+value.currentDebt + '</td>';mdata += '<td>'+value.totalCash + '</td>';mdata += '<td>'+value.totalDebt + '</td>';mdata += '<td>'+value.shareholderEquity + '</td>';mdata += '<td>'+value.cashChange + '</td>';mdata += '<td>'+value.cashFlow + '</td>';mdata += '<td>'+value.operatingGainsLosses + '</td>';mdata += '</tr>';});mdata += "</tbody></table>";displayResources.html(mdata);$("table").addClass("table");});});


$("#retrieve-financials-Sony").click(function(){var displayResources = $("#display-financials-Sony");+displayResources.text("Loading data from JSON source...");$.getJSON("https://api.iextrading.com/1.0/stock/SNE/financials?period=annual", function (data) {var mdata ="<table><thead><tr><th>symbol</th><th>reportDate</th><th>grossProfit</th><th>costOfRevenue</th><th>operatingRevenue</th><th>totalRevenue</th><th>operatingIncome</th><th>netIncome</th><th>researchAndDevelopment</th><th>operatingExpense</th><th>currentAssets</th><th>totalAssets</th><th>totalLiabilities</th><th>currentCash</th><th>currentDebt</th><th>totalCash</th><th>totalDebt</th><th>shareholderEquity</th><th>cashChange</th><th>cashFlow</th><th>operatingGainsLosses</th></thead><tbody>";$.each(data['financials'], function (key, value) {mdata += '<tr>';mdata += '<td>'+data.symbol + '</td>';mdata += '<td>'+value.reportDate + '</td>';mdata += '<td>'+value.grossProfit + '</td>';mdata += '<td>'+value.costOfRevenue + '</td>';mdata += '<td>'+value.operatingRevenue + '</td>';mdata += '<td>'+value.totalRevenue + '</td>';mdata += '<td>'+value.operatingIncome + '</td>';mdata += '<td>'+value.netIncome + '</td>';mdata += '<td>'+value.researchAndDevelopment + '</td>';mdata += '<td>'+value.operatingExpense + '</td>';mdata += '<td>'+value.currentAssets + '</td>';mdata += '<td>'+value.totalAssets + '</td>';mdata += '<td>'+value.totalLiabilities + '</td>';mdata += '<td>'+value.currentCash + '</td>';mdata += '<td>'+value.currentDebt + '</td>';mdata += '<td>'+value.totalCash + '</td>';mdata += '<td>'+value.totalDebt + '</td>';mdata += '<td>'+value.shareholderEquity + '</td>';mdata += '<td>'+value.cashChange + '</td>';mdata += '<td>'+value.cashFlow + '</td>';mdata += '<td>'+value.operatingGainsLosses + '</td>';mdata += '</tr>';});mdata += "</tbody></table>";displayResources.html(mdata);$("table").addClass("table");});});


$("#retrieve-financials-Costco").click(function(){var displayResources = $("#display-financials-Costco");+displayResources.text("Loading data from JSON source...");$.getJSON("https://api.iextrading.com/1.0/stock/COST/financials?period=annual", function (data) {var mdata ="<table><thead><tr><th>symbol</th><th>reportDate</th><th>grossProfit</th><th>costOfRevenue</th><th>operatingRevenue</th><th>totalRevenue</th><th>operatingIncome</th><th>netIncome</th><th>researchAndDevelopment</th><th>operatingExpense</th><th>currentAssets</th><th>totalAssets</th><th>totalLiabilities</th><th>currentCash</th><th>currentDebt</th><th>totalCash</th><th>totalDebt</th><th>shareholderEquity</th><th>cashChange</th><th>cashFlow</th><th>operatingGainsLosses</th></thead><tbody>";$.each(data['financials'], function (key, value) {mdata += '<tr>';mdata += '<td>'+data.symbol + '</td>';mdata += '<td>'+value.reportDate + '</td>';mdata += '<td>'+value.grossProfit + '</td>';mdata += '<td>'+value.costOfRevenue + '</td>';mdata += '<td>'+value.operatingRevenue + '</td>';mdata += '<td>'+value.totalRevenue + '</td>';mdata += '<td>'+value.operatingIncome + '</td>';mdata += '<td>'+value.netIncome + '</td>';mdata += '<td>'+value.researchAndDevelopment + '</td>';mdata += '<td>'+value.operatingExpense + '</td>';mdata += '<td>'+value.currentAssets + '</td>';mdata += '<td>'+value.totalAssets + '</td>';mdata += '<td>'+value.totalLiabilities + '</td>';mdata += '<td>'+value.currentCash + '</td>';mdata += '<td>'+value.currentDebt + '</td>';mdata += '<td>'+value.totalCash + '</td>';mdata += '<td>'+value.totalDebt + '</td>';mdata += '<td>'+value.shareholderEquity + '</td>';mdata += '<td>'+value.cashChange + '</td>';mdata += '<td>'+value.cashFlow + '</td>';mdata += '<td>'+value.operatingGainsLosses + '</td>';mdata += '</tr>';});mdata += "</tbody></table>";displayResources.html(mdata);$("table").addClass("table");});});


$("#retrieve-financials-Conocophillips").click(function(){var displayResources = $("#display-financials-Conocophillips");+displayResources.text("Loading data from JSON source...");$.getJSON("https://api.iextrading.com/1.0/stock/COP/financials?period=annual", function (data) {var mdata ="<table><thead><tr><th>symbol</th><th>reportDate</th><th>grossProfit</th><th>costOfRevenue</th><th>operatingRevenue</th><th>totalRevenue</th><th>operatingIncome</th><th>netIncome</th><th>researchAndDevelopment</th><th>operatingExpense</th><th>currentAssets</th><th>totalAssets</th><th>totalLiabilities</th><th>currentCash</th><th>currentDebt</th><th>totalCash</th><th>totalDebt</th><th>shareholderEquity</th><th>cashChange</th><th>cashFlow</th><th>operatingGainsLosses</th></thead><tbody>";$.each(data['financials'], function (key, value) {mdata += '<tr>';mdata += '<td>'+data.symbol + '</td>';mdata += '<td>'+value.reportDate + '</td>';mdata += '<td>'+value.grossProfit + '</td>';mdata += '<td>'+value.costOfRevenue + '</td>';mdata += '<td>'+value.operatingRevenue + '</td>';mdata += '<td>'+value.totalRevenue + '</td>';mdata += '<td>'+value.operatingIncome + '</td>';mdata += '<td>'+value.netIncome + '</td>';mdata += '<td>'+value.researchAndDevelopment + '</td>';mdata += '<td>'+value.operatingExpense + '</td>';mdata += '<td>'+value.currentAssets + '</td>';mdata += '<td>'+value.totalAssets + '</td>';mdata += '<td>'+value.totalLiabilities + '</td>';mdata += '<td>'+value.currentCash + '</td>';mdata += '<td>'+value.currentDebt + '</td>';mdata += '<td>'+value.totalCash + '</td>';mdata += '<td>'+value.totalDebt + '</td>';mdata += '<td>'+value.shareholderEquity + '</td>';mdata += '<td>'+value.cashChange + '</td>';mdata += '<td>'+value.cashFlow + '</td>';mdata += '<td>'+value.operatingGainsLosses + '</td>';mdata += '</tr>';});mdata += "</tbody></table>";displayResources.html(mdata);$("table").addClass("table");});});


$("#retrieve-financials-SynchronyFinancial").click(function(){var displayResources = $("#display-financials-SynchronyFinancial");+displayResources.text("Loading data from JSON source...");$.getJSON("https://api.iextrading.com/1.0/stock/SYF/financials?period=annual", function (data) {var mdata ="<table><thead><tr><th>symbol</th><th>reportDate</th><th>grossProfit</th><th>costOfRevenue</th><th>operatingRevenue</th><th>totalRevenue</th><th>operatingIncome</th><th>netIncome</th><th>researchAndDevelopment</th><th>operatingExpense</th><th>currentAssets</th><th>totalAssets</th><th>totalLiabilities</th><th>currentCash</th><th>currentDebt</th><th>totalCash</th><th>totalDebt</th><th>shareholderEquity</th><th>cashChange</th><th>cashFlow</th><th>operatingGainsLosses</th></thead><tbody>";$.each(data['financials'], function (key, value) {mdata += '<tr>';mdata += '<td>'+data.symbol + '</td>';mdata += '<td>'+value.reportDate + '</td>';mdata += '<td>'+value.grossProfit + '</td>';mdata += '<td>'+value.costOfRevenue + '</td>';mdata += '<td>'+value.operatingRevenue + '</td>';mdata += '<td>'+value.totalRevenue + '</td>';mdata += '<td>'+value.operatingIncome + '</td>';mdata += '<td>'+value.netIncome + '</td>';mdata += '<td>'+value.researchAndDevelopment + '</td>';mdata += '<td>'+value.operatingExpense + '</td>';mdata += '<td>'+value.currentAssets + '</td>';mdata += '<td>'+value.totalAssets + '</td>';mdata += '<td>'+value.totalLiabilities + '</td>';mdata += '<td>'+value.currentCash + '</td>';mdata += '<td>'+value.currentDebt + '</td>';mdata += '<td>'+value.totalCash + '</td>';mdata += '<td>'+value.totalDebt + '</td>';mdata += '<td>'+value.shareholderEquity + '</td>';mdata += '<td>'+value.cashChange + '</td>';mdata += '<td>'+value.cashFlow + '</td>';mdata += '<td>'+value.operatingGainsLosses + '</td>';mdata += '</tr>';});mdata += "</tbody></table>";displayResources.html(mdata);$("table").addClass("table");});});


$("#retrieve-financials-CapitalOne").click(function(){var displayResources = $("#display-financials-CapitalOne");+displayResources.text("Loading data from JSON source...");$.getJSON("https://api.iextrading.com/1.0/stock/COF/financials?period=annual", function (data) {var mdata ="<table><thead><tr><th>symbol</th><th>reportDate</th><th>grossProfit</th><th>costOfRevenue</th><th>operatingRevenue</th><th>totalRevenue</th><th>operatingIncome</th><th>netIncome</th><th>researchAndDevelopment</th><th>operatingExpense</th><th>currentAssets</th><th>totalAssets</th><th>totalLiabilities</th><th>currentCash</th><th>currentDebt</th><th>totalCash</th><th>totalDebt</th><th>shareholderEquity</th><th>cashChange</th><th>cashFlow</th><th>operatingGainsLosses</th></thead><tbody>";$.each(data['financials'], function (key, value) {mdata += '<tr>';mdata += '<td>'+data.symbol + '</td>';mdata += '<td>'+value.reportDate + '</td>';mdata += '<td>'+value.grossProfit + '</td>';mdata += '<td>'+value.costOfRevenue + '</td>';mdata += '<td>'+value.operatingRevenue + '</td>';mdata += '<td>'+value.totalRevenue + '</td>';mdata += '<td>'+value.operatingIncome + '</td>';mdata += '<td>'+value.netIncome + '</td>';mdata += '<td>'+value.researchAndDevelopment + '</td>';mdata += '<td>'+value.operatingExpense + '</td>';mdata += '<td>'+value.currentAssets + '</td>';mdata += '<td>'+value.totalAssets + '</td>';mdata += '<td>'+value.totalLiabilities + '</td>';mdata += '<td>'+value.currentCash + '</td>';mdata += '<td>'+value.currentDebt + '</td>';mdata += '<td>'+value.totalCash + '</td>';mdata += '<td>'+value.totalDebt + '</td>';mdata += '<td>'+value.shareholderEquity + '</td>';mdata += '<td>'+value.cashChange + '</td>';mdata += '<td>'+value.cashFlow + '</td>';mdata += '<td>'+value.operatingGainsLosses + '</td>';mdata += '</tr>';});mdata += "</tbody></table>";displayResources.html(mdata);$("table").addClass("table");});});


$("#retrieve-financials-BankOfMontreal").click(function(){var displayResources = $("#display-financials-BankOfMontreal");+displayResources.text("Loading data from JSON source...");$.getJSON("https://api.iextrading.com/1.0/stock/BMO/financials?period=annual", function (data) {var mdata ="<table><thead><tr><th>symbol</th><th>reportDate</th><th>grossProfit</th><th>costOfRevenue</th><th>operatingRevenue</th><th>totalRevenue</th><th>operatingIncome</th><th>netIncome</th><th>researchAndDevelopment</th><th>operatingExpense</th><th>currentAssets</th><th>totalAssets</th><th>totalLiabilities</th><th>currentCash</th><th>currentDebt</th><th>totalCash</th><th>totalDebt</th><th>shareholderEquity</th><th>cashChange</th><th>cashFlow</th><th>operatingGainsLosses</th></thead><tbody>";$.each(data['financials'], function (key, value) {mdata += '<tr>';mdata += '<td>'+data.symbol + '</td>';mdata += '<td>'+value.reportDate + '</td>';mdata += '<td>'+value.grossProfit + '</td>';mdata += '<td>'+value.costOfRevenue + '</td>';mdata += '<td>'+value.operatingRevenue + '</td>';mdata += '<td>'+value.totalRevenue + '</td>';mdata += '<td>'+value.operatingIncome + '</td>';mdata += '<td>'+value.netIncome + '</td>';mdata += '<td>'+value.researchAndDevelopment + '</td>';mdata += '<td>'+value.operatingExpense + '</td>';mdata += '<td>'+value.currentAssets + '</td>';mdata += '<td>'+value.totalAssets + '</td>';mdata += '<td>'+value.totalLiabilities + '</td>';mdata += '<td>'+value.currentCash + '</td>';mdata += '<td>'+value.currentDebt + '</td>';mdata += '<td>'+value.totalCash + '</td>';mdata += '<td>'+value.totalDebt + '</td>';mdata += '<td>'+value.shareholderEquity + '</td>';mdata += '<td>'+value.cashChange + '</td>';mdata += '<td>'+value.cashFlow + '</td>';mdata += '<td>'+value.operatingGainsLosses + '</td>';mdata += '</tr>';});mdata += "</tbody></table>";displayResources.html(mdata);$("table").addClass("table");});});


$("#retrieve-financials-BristolMyers").click(function(){var displayResources = $("#display-financials-BristolMyers");+displayResources.text("Loading data from JSON source...");$.getJSON("https://api.iextrading.com/1.0/stock/BMY/financials?period=annual", function (data) {var mdata ="<table><thead><tr><th>symbol</th><th>reportDate</th><th>grossProfit</th><th>costOfRevenue</th><th>operatingRevenue</th><th>totalRevenue</th><th>operatingIncome</th><th>netIncome</th><th>researchAndDevelopment</th><th>operatingExpense</th><th>currentAssets</th><th>totalAssets</th><th>totalLiabilities</th><th>currentCash</th><th>currentDebt</th><th>totalCash</th><th>totalDebt</th><th>shareholderEquity</th><th>cashChange</th><th>cashFlow</th><th>operatingGainsLosses</th></thead><tbody>";$.each(data['financials'], function (key, value) {mdata += '<tr>';mdata += '<td>'+data.symbol + '</td>';mdata += '<td>'+value.reportDate + '</td>';mdata += '<td>'+value.grossProfit + '</td>';mdata += '<td>'+value.costOfRevenue + '</td>';mdata += '<td>'+value.operatingRevenue + '</td>';mdata += '<td>'+value.totalRevenue + '</td>';mdata += '<td>'+value.operatingIncome + '</td>';mdata += '<td>'+value.netIncome + '</td>';mdata += '<td>'+value.researchAndDevelopment + '</td>';mdata += '<td>'+value.operatingExpense + '</td>';mdata += '<td>'+value.currentAssets + '</td>';mdata += '<td>'+value.totalAssets + '</td>';mdata += '<td>'+value.totalLiabilities + '</td>';mdata += '<td>'+value.currentCash + '</td>';mdata += '<td>'+value.currentDebt + '</td>';mdata += '<td>'+value.totalCash + '</td>';mdata += '<td>'+value.totalDebt + '</td>';mdata += '<td>'+value.shareholderEquity + '</td>';mdata += '<td>'+value.cashChange + '</td>';mdata += '<td>'+value.cashFlow + '</td>';mdata += '<td>'+value.operatingGainsLosses + '</td>';mdata += '</tr>';});mdata += "</tbody></table>";displayResources.html(mdata);$("table").addClass("table");});});


$("#retrieve-financials-Raytheon").click(function(){var displayResources = $("#display-financials-Raytheon");+displayResources.text("Loading data from JSON source...");$.getJSON("https://api.iextrading.com/1.0/stock/RTN/financials?period=annual", function (data) {var mdata ="<table><thead><tr><th>symbol</th><th>reportDate</th><th>grossProfit</th><th>costOfRevenue</th><th>operatingRevenue</th><th>totalRevenue</th><th>operatingIncome</th><th>netIncome</th><th>researchAndDevelopment</th><th>operatingExpense</th><th>currentAssets</th><th>totalAssets</th><th>totalLiabilities</th><th>currentCash</th><th>currentDebt</th><th>totalCash</th><th>totalDebt</th><th>shareholderEquity</th><th>cashChange</th><th>cashFlow</th><th>operatingGainsLosses</th></thead><tbody>";$.each(data['financials'], function (key, value) {mdata += '<tr>';mdata += '<td>'+data.symbol + '</td>';mdata += '<td>'+value.reportDate + '</td>';mdata += '<td>'+value.grossProfit + '</td>';mdata += '<td>'+value.costOfRevenue + '</td>';mdata += '<td>'+value.operatingRevenue + '</td>';mdata += '<td>'+value.totalRevenue + '</td>';mdata += '<td>'+value.operatingIncome + '</td>';mdata += '<td>'+value.netIncome + '</td>';mdata += '<td>'+value.researchAndDevelopment + '</td>';mdata += '<td>'+value.operatingExpense + '</td>';mdata += '<td>'+value.currentAssets + '</td>';mdata += '<td>'+value.totalAssets + '</td>';mdata += '<td>'+value.totalLiabilities + '</td>';mdata += '<td>'+value.currentCash + '</td>';mdata += '<td>'+value.currentDebt + '</td>';mdata += '<td>'+value.totalCash + '</td>';mdata += '<td>'+value.totalDebt + '</td>';mdata += '<td>'+value.shareholderEquity + '</td>';mdata += '<td>'+value.cashChange + '</td>';mdata += '<td>'+value.cashFlow + '</td>';mdata += '<td>'+value.operatingGainsLosses + '</td>';mdata += '</tr>';});mdata += "</tbody></table>";displayResources.html(mdata);$("table").addClass("table");});});


$("#retrieve-financials-Dell").click(function(){var displayResources = $("#display-financials-Dell");+displayResources.text("Loading data from JSON source...");$.getJSON("https://api.iextrading.com/1.0/stock/DVMT/financials?period=annual", function (data) {var mdata ="<table><thead><tr><th>symbol</th><th>reportDate</th><th>grossProfit</th><th>costOfRevenue</th><th>operatingRevenue</th><th>totalRevenue</th><th>operatingIncome</th><th>netIncome</th><th>researchAndDevelopment</th><th>operatingExpense</th><th>currentAssets</th><th>totalAssets</th><th>totalLiabilities</th><th>currentCash</th><th>currentDebt</th><th>totalCash</th><th>totalDebt</th><th>shareholderEquity</th><th>cashChange</th><th>cashFlow</th><th>operatingGainsLosses</th></thead><tbody>";$.each(data['financials'], function (key, value) {mdata += '<tr>';mdata += '<td>'+data.symbol + '</td>';mdata += '<td>'+value.reportDate + '</td>';mdata += '<td>'+value.grossProfit + '</td>';mdata += '<td>'+value.costOfRevenue + '</td>';mdata += '<td>'+value.operatingRevenue + '</td>';mdata += '<td>'+value.totalRevenue + '</td>';mdata += '<td>'+value.operatingIncome + '</td>';mdata += '<td>'+value.netIncome + '</td>';mdata += '<td>'+value.researchAndDevelopment + '</td>';mdata += '<td>'+value.operatingExpense + '</td>';mdata += '<td>'+value.currentAssets + '</td>';mdata += '<td>'+value.totalAssets + '</td>';mdata += '<td>'+value.totalLiabilities + '</td>';mdata += '<td>'+value.currentCash + '</td>';mdata += '<td>'+value.currentDebt + '</td>';mdata += '<td>'+value.totalCash + '</td>';mdata += '<td>'+value.totalDebt + '</td>';mdata += '<td>'+value.shareholderEquity + '</td>';mdata += '<td>'+value.cashChange + '</td>';mdata += '<td>'+value.cashFlow + '</td>';mdata += '<td>'+value.operatingGainsLosses + '</td>';mdata += '</tr>';});mdata += "</tbody></table>";displayResources.html(mdata);$("table").addClass("table");});});


$("#retrieve-financials-HewlettPackard").click(function(){var displayResources = $("#display-financials-HewlettPackard");+displayResources.text("Loading data from JSON source...");$.getJSON("https://api.iextrading.com/1.0/stock/HPE/financials?period=annual", function (data) {var mdata ="<table><thead><tr><th>symbol</th><th>reportDate</th><th>grossProfit</th><th>costOfRevenue</th><th>operatingRevenue</th><th>totalRevenue</th><th>operatingIncome</th><th>netIncome</th><th>researchAndDevelopment</th><th>operatingExpense</th><th>currentAssets</th><th>totalAssets</th><th>totalLiabilities</th><th>currentCash</th><th>currentDebt</th><th>totalCash</th><th>totalDebt</th><th>shareholderEquity</th><th>cashChange</th><th>cashFlow</th><th>operatingGainsLosses</th></thead><tbody>";$.each(data['financials'], function (key, value) {mdata += '<tr>';mdata += '<td>'+data.symbol + '</td>';mdata += '<td>'+value.reportDate + '</td>';mdata += '<td>'+value.grossProfit + '</td>';mdata += '<td>'+value.costOfRevenue + '</td>';mdata += '<td>'+value.operatingRevenue + '</td>';mdata += '<td>'+value.totalRevenue + '</td>';mdata += '<td>'+value.operatingIncome + '</td>';mdata += '<td>'+value.netIncome + '</td>';mdata += '<td>'+value.researchAndDevelopment + '</td>';mdata += '<td>'+value.operatingExpense + '</td>';mdata += '<td>'+value.currentAssets + '</td>';mdata += '<td>'+value.totalAssets + '</td>';mdata += '<td>'+value.totalLiabilities + '</td>';mdata += '<td>'+value.currentCash + '</td>';mdata += '<td>'+value.currentDebt + '</td>';mdata += '<td>'+value.totalCash + '</td>';mdata += '<td>'+value.totalDebt + '</td>';mdata += '<td>'+value.shareholderEquity + '</td>';mdata += '<td>'+value.cashChange + '</td>';mdata += '<td>'+value.cashFlow + '</td>';mdata += '<td>'+value.operatingGainsLosses + '</td>';mdata += '</tr>';});mdata += "</tbody></table>";displayResources.html(mdata);$("table").addClass("table");});});


$("#retrieve-financials-HP").click(function(){var displayResources = $("#display-financials-HP");+displayResources.text("Loading data from JSON source...");$.getJSON("https://api.iextrading.com/1.0/stock/HPQ/financials?period=annual", function (data) {var mdata ="<table><thead><tr><th>symbol</th><th>reportDate</th><th>grossProfit</th><th>costOfRevenue</th><th>operatingRevenue</th><th>totalRevenue</th><th>operatingIncome</th><th>netIncome</th><th>researchAndDevelopment</th><th>operatingExpense</th><th>currentAssets</th><th>totalAssets</th><th>totalLiabilities</th><th>currentCash</th><th>currentDebt</th><th>totalCash</th><th>totalDebt</th><th>shareholderEquity</th><th>cashChange</th><th>cashFlow</th><th>operatingGainsLosses</th></thead><tbody>";$.each(data['financials'], function (key, value) {mdata += '<tr>';mdata += '<td>'+data.symbol + '</td>';mdata += '<td>'+value.reportDate + '</td>';mdata += '<td>'+value.grossProfit + '</td>';mdata += '<td>'+value.costOfRevenue + '</td>';mdata += '<td>'+value.operatingRevenue + '</td>';mdata += '<td>'+value.totalRevenue + '</td>';mdata += '<td>'+value.operatingIncome + '</td>';mdata += '<td>'+value.netIncome + '</td>';mdata += '<td>'+value.researchAndDevelopment + '</td>';mdata += '<td>'+value.operatingExpense + '</td>';mdata += '<td>'+value.currentAssets + '</td>';mdata += '<td>'+value.totalAssets + '</td>';mdata += '<td>'+value.totalLiabilities + '</td>';mdata += '<td>'+value.currentCash + '</td>';mdata += '<td>'+value.currentDebt + '</td>';mdata += '<td>'+value.totalCash + '</td>';mdata += '<td>'+value.totalDebt + '</td>';mdata += '<td>'+value.shareholderEquity + '</td>';mdata += '<td>'+value.cashChange + '</td>';mdata += '<td>'+value.cashFlow + '</td>';mdata += '<td>'+value.operatingGainsLosses + '</td>';mdata += '</tr>';});mdata += "</tbody></table>";displayResources.html(mdata);$("table").addClass("table");});});


$("#retrieve-financials-Intuit").click(function(){var displayResources = $("#display-financials-Intuit");+displayResources.text("Loading data from JSON source...");$.getJSON("https://api.iextrading.com/1.0/stock/INTU/financials?period=annual", function (data) {var mdata ="<table><thead><tr><th>symbol</th><th>reportDate</th><th>grossProfit</th><th>costOfRevenue</th><th>operatingRevenue</th><th>totalRevenue</th><th>operatingIncome</th><th>netIncome</th><th>researchAndDevelopment</th><th>operatingExpense</th><th>currentAssets</th><th>totalAssets</th><th>totalLiabilities</th><th>currentCash</th><th>currentDebt</th><th>totalCash</th><th>totalDebt</th><th>shareholderEquity</th><th>cashChange</th><th>cashFlow</th><th>operatingGainsLosses</th></thead><tbody>";$.each(data['financials'], function (key, value) {mdata += '<tr>';mdata += '<td>'+data.symbol + '</td>';mdata += '<td>'+value.reportDate + '</td>';mdata += '<td>'+value.grossProfit + '</td>';mdata += '<td>'+value.costOfRevenue + '</td>';mdata += '<td>'+value.operatingRevenue + '</td>';mdata += '<td>'+value.totalRevenue + '</td>';mdata += '<td>'+value.operatingIncome + '</td>';mdata += '<td>'+value.netIncome + '</td>';mdata += '<td>'+value.researchAndDevelopment + '</td>';mdata += '<td>'+value.operatingExpense + '</td>';mdata += '<td>'+value.currentAssets + '</td>';mdata += '<td>'+value.totalAssets + '</td>';mdata += '<td>'+value.totalLiabilities + '</td>';mdata += '<td>'+value.currentCash + '</td>';mdata += '<td>'+value.currentDebt + '</td>';mdata += '<td>'+value.totalCash + '</td>';mdata += '<td>'+value.totalDebt + '</td>';mdata += '<td>'+value.shareholderEquity + '</td>';mdata += '<td>'+value.cashChange + '</td>';mdata += '<td>'+value.cashFlow + '</td>';mdata += '<td>'+value.operatingGainsLosses + '</td>';mdata += '</tr>';});mdata += "</tbody></table>";displayResources.html(mdata);$("table").addClass("table");});});


$("#retrieve-financials-Bandwidth").click(function(){var displayResources = $("#display-financials-Bandwidth");+displayResources.text("Loading data from JSON source...");$.getJSON("https://api.iextrading.com/1.0/stock/BAND/financials?period=annual", function (data) {var mdata ="<table><thead><tr><th>symbol</th><th>reportDate</th><th>grossProfit</th><th>costOfRevenue</th><th>operatingRevenue</th><th>totalRevenue</th><th>operatingIncome</th><th>netIncome</th><th>researchAndDevelopment</th><th>operatingExpense</th><th>currentAssets</th><th>totalAssets</th><th>totalLiabilities</th><th>currentCash</th><th>currentDebt</th><th>totalCash</th><th>totalDebt</th><th>shareholderEquity</th><th>cashChange</th><th>cashFlow</th><th>operatingGainsLosses</th></thead><tbody>";$.each(data['financials'], function (key, value) {mdata += '<tr>';mdata += '<td>'+data.symbol + '</td>';mdata += '<td>'+value.reportDate + '</td>';mdata += '<td>'+value.grossProfit + '</td>';mdata += '<td>'+value.costOfRevenue + '</td>';mdata += '<td>'+value.operatingRevenue + '</td>';mdata += '<td>'+value.totalRevenue + '</td>';mdata += '<td>'+value.operatingIncome + '</td>';mdata += '<td>'+value.netIncome + '</td>';mdata += '<td>'+value.researchAndDevelopment + '</td>';mdata += '<td>'+value.operatingExpense + '</td>';mdata += '<td>'+value.currentAssets + '</td>';mdata += '<td>'+value.totalAssets + '</td>';mdata += '<td>'+value.totalLiabilities + '</td>';mdata += '<td>'+value.currentCash + '</td>';mdata += '<td>'+value.currentDebt + '</td>';mdata += '<td>'+value.totalCash + '</td>';mdata += '<td>'+value.totalDebt + '</td>';mdata += '<td>'+value.shareholderEquity + '</td>';mdata += '<td>'+value.cashChange + '</td>';mdata += '<td>'+value.cashFlow + '</td>';mdata += '<td>'+value.operatingGainsLosses + '</td>';mdata += '</tr>';});mdata += "</tbody></table>";displayResources.html(mdata);$("table").addClass("table");});});


$("#retrieve-financials-BuckleInc").click(function(){var displayResources = $("#display-financials-BuckleInc");+displayResources.text("Loading data from JSON source...");$.getJSON("https://api.iextrading.com/1.0/stock/BKE/financials?period=annual", function (data) {var mdata ="<table><thead><tr><th>symbol</th><th>reportDate</th><th>grossProfit</th><th>costOfRevenue</th><th>operatingRevenue</th><th>totalRevenue</th><th>operatingIncome</th><th>netIncome</th><th>researchAndDevelopment</th><th>operatingExpense</th><th>currentAssets</th><th>totalAssets</th><th>totalLiabilities</th><th>currentCash</th><th>currentDebt</th><th>totalCash</th><th>totalDebt</th><th>shareholderEquity</th><th>cashChange</th><th>cashFlow</th><th>operatingGainsLosses</th></thead><tbody>";$.each(data['financials'], function (key, value) {mdata += '<tr>';mdata += '<td>'+data.symbol + '</td>';mdata += '<td>'+value.reportDate + '</td>';mdata += '<td>'+value.grossProfit + '</td>';mdata += '<td>'+value.costOfRevenue + '</td>';mdata += '<td>'+value.operatingRevenue + '</td>';mdata += '<td>'+value.totalRevenue + '</td>';mdata += '<td>'+value.operatingIncome + '</td>';mdata += '<td>'+value.netIncome + '</td>';mdata += '<td>'+value.researchAndDevelopment + '</td>';mdata += '<td>'+value.operatingExpense + '</td>';mdata += '<td>'+value.currentAssets + '</td>';mdata += '<td>'+value.totalAssets + '</td>';mdata += '<td>'+value.totalLiabilities + '</td>';mdata += '<td>'+value.currentCash + '</td>';mdata += '<td>'+value.currentDebt + '</td>';mdata += '<td>'+value.totalCash + '</td>';mdata += '<td>'+value.totalDebt + '</td>';mdata += '<td>'+value.shareholderEquity + '</td>';mdata += '<td>'+value.cashChange + '</td>';mdata += '<td>'+value.cashFlow + '</td>';mdata += '<td>'+value.operatingGainsLosses + '</td>';mdata += '</tr>';});mdata += "</tbody></table>";displayResources.html(mdata);$("table").addClass("table");});});


$("#retrieve-financials-BJsRestaurant").click(function(){var displayResources = $("#display-financials-BJsRestaurant");+displayResources.text("Loading data from JSON source...");$.getJSON("https://api.iextrading.com/1.0/stock/BJRI/financials?period=annual", function (data) {var mdata ="<table><thead><tr><th>symbol</th><th>reportDate</th><th>grossProfit</th><th>costOfRevenue</th><th>operatingRevenue</th><th>totalRevenue</th><th>operatingIncome</th><th>netIncome</th><th>researchAndDevelopment</th><th>operatingExpense</th><th>currentAssets</th><th>totalAssets</th><th>totalLiabilities</th><th>currentCash</th><th>currentDebt</th><th>totalCash</th><th>totalDebt</th><th>shareholderEquity</th><th>cashChange</th><th>cashFlow</th><th>operatingGainsLosses</th></thead><tbody>";$.each(data['financials'], function (key, value) {mdata += '<tr>';mdata += '<td>'+data.symbol + '</td>';mdata += '<td>'+value.reportDate + '</td>';mdata += '<td>'+value.grossProfit + '</td>';mdata += '<td>'+value.costOfRevenue + '</td>';mdata += '<td>'+value.operatingRevenue + '</td>';mdata += '<td>'+value.totalRevenue + '</td>';mdata += '<td>'+value.operatingIncome + '</td>';mdata += '<td>'+value.netIncome + '</td>';mdata += '<td>'+value.researchAndDevelopment + '</td>';mdata += '<td>'+value.operatingExpense + '</td>';mdata += '<td>'+value.currentAssets + '</td>';mdata += '<td>'+value.totalAssets + '</td>';mdata += '<td>'+value.totalLiabilities + '</td>';mdata += '<td>'+value.currentCash + '</td>';mdata += '<td>'+value.currentDebt + '</td>';mdata += '<td>'+value.totalCash + '</td>';mdata += '<td>'+value.totalDebt + '</td>';mdata += '<td>'+value.shareholderEquity + '</td>';mdata += '<td>'+value.cashChange + '</td>';mdata += '<td>'+value.cashFlow + '</td>';mdata += '<td>'+value.operatingGainsLosses + '</td>';mdata += '</tr>';});mdata += "</tbody></table>";displayResources.html(mdata);$("table").addClass("table");});});


$("#retrieve-financials-GibraltarIndustries").click(function(){var displayResources = $("#display-financials-GibraltarIndustries");+displayResources.text("Loading data from JSON source...");$.getJSON("https://api.iextrading.com/1.0/stock/ROCK/financials?period=annual", function (data) {var mdata ="<table><thead><tr><th>symbol</th><th>reportDate</th><th>grossProfit</th><th>costOfRevenue</th><th>operatingRevenue</th><th>totalRevenue</th><th>operatingIncome</th><th>netIncome</th><th>researchAndDevelopment</th><th>operatingExpense</th><th>currentAssets</th><th>totalAssets</th><th>totalLiabilities</th><th>currentCash</th><th>currentDebt</th><th>totalCash</th><th>totalDebt</th><th>shareholderEquity</th><th>cashChange</th><th>cashFlow</th><th>operatingGainsLosses</th></thead><tbody>";$.each(data['financials'], function (key, value) {mdata += '<tr>';mdata += '<td>'+data.symbol + '</td>';mdata += '<td>'+value.reportDate + '</td>';mdata += '<td>'+value.grossProfit + '</td>';mdata += '<td>'+value.costOfRevenue + '</td>';mdata += '<td>'+value.operatingRevenue + '</td>';mdata += '<td>'+value.totalRevenue + '</td>';mdata += '<td>'+value.operatingIncome + '</td>';mdata += '<td>'+value.netIncome + '</td>';mdata += '<td>'+value.researchAndDevelopment + '</td>';mdata += '<td>'+value.operatingExpense + '</td>';mdata += '<td>'+value.currentAssets + '</td>';mdata += '<td>'+value.totalAssets + '</td>';mdata += '<td>'+value.totalLiabilities + '</td>';mdata += '<td>'+value.currentCash + '</td>';mdata += '<td>'+value.currentDebt + '</td>';mdata += '<td>'+value.totalCash + '</td>';mdata += '<td>'+value.totalDebt + '</td>';mdata += '<td>'+value.shareholderEquity + '</td>';mdata += '<td>'+value.cashChange + '</td>';mdata += '<td>'+value.cashFlow + '</td>';mdata += '<td>'+value.operatingGainsLosses + '</td>';mdata += '</tr>';});mdata += "</tbody></table>";displayResources.html(mdata);$("table").addClass("table");});});


$("#retrieve-financials-MarcusandMillichapInc").click(function(){var displayResources = $("#display-financials-MarcusandMillichapInc");+displayResources.text("Loading data from JSON source...");$.getJSON("https://api.iextrading.com/1.0/stock/MMI/financials?period=annual", function (data) {var mdata ="<table><thead><tr><th>symbol</th><th>reportDate</th><th>grossProfit</th><th>costOfRevenue</th><th>operatingRevenue</th><th>totalRevenue</th><th>operatingIncome</th><th>netIncome</th><th>researchAndDevelopment</th><th>operatingExpense</th><th>currentAssets</th><th>totalAssets</th><th>totalLiabilities</th><th>currentCash</th><th>currentDebt</th><th>totalCash</th><th>totalDebt</th><th>shareholderEquity</th><th>cashChange</th><th>cashFlow</th><th>operatingGainsLosses</th></thead><tbody>";$.each(data['financials'], function (key, value) {mdata += '<tr>';mdata += '<td>'+data.symbol + '</td>';mdata += '<td>'+value.reportDate + '</td>';mdata += '<td>'+value.grossProfit + '</td>';mdata += '<td>'+value.costOfRevenue + '</td>';mdata += '<td>'+value.operatingRevenue + '</td>';mdata += '<td>'+value.totalRevenue + '</td>';mdata += '<td>'+value.operatingIncome + '</td>';mdata += '<td>'+value.netIncome + '</td>';mdata += '<td>'+value.researchAndDevelopment + '</td>';mdata += '<td>'+value.operatingExpense + '</td>';mdata += '<td>'+value.currentAssets + '</td>';mdata += '<td>'+value.totalAssets + '</td>';mdata += '<td>'+value.totalLiabilities + '</td>';mdata += '<td>'+value.currentCash + '</td>';mdata += '<td>'+value.currentDebt + '</td>';mdata += '<td>'+value.totalCash + '</td>';mdata += '<td>'+value.totalDebt + '</td>';mdata += '<td>'+value.shareholderEquity + '</td>';mdata += '<td>'+value.cashChange + '</td>';mdata += '<td>'+value.cashFlow + '</td>';mdata += '<td>'+value.operatingGainsLosses + '</td>';mdata += '</tr>';});mdata += "</tbody></table>";displayResources.html(mdata);$("table").addClass("table");});});


$("#retrieve-financials-AngiHomeServices").click(function(){var displayResources = $("#display-financials-AngiHomeServices");+displayResources.text("Loading data from JSON source...");$.getJSON("https://api.iextrading.com/1.0/stock/ANGI/financials?period=annual", function (data) {var mdata ="<table><thead><tr><th>symbol</th><th>reportDate</th><th>grossProfit</th><th>costOfRevenue</th><th>operatingRevenue</th><th>totalRevenue</th><th>operatingIncome</th><th>netIncome</th><th>researchAndDevelopment</th><th>operatingExpense</th><th>currentAssets</th><th>totalAssets</th><th>totalLiabilities</th><th>currentCash</th><th>currentDebt</th><th>totalCash</th><th>totalDebt</th><th>shareholderEquity</th><th>cashChange</th><th>cashFlow</th><th>operatingGainsLosses</th></thead><tbody>";$.each(data['financials'], function (key, value) {mdata += '<tr>';mdata += '<td>'+data.symbol + '</td>';mdata += '<td>'+value.reportDate + '</td>';mdata += '<td>'+value.grossProfit + '</td>';mdata += '<td>'+value.costOfRevenue + '</td>';mdata += '<td>'+value.operatingRevenue + '</td>';mdata += '<td>'+value.totalRevenue + '</td>';mdata += '<td>'+value.operatingIncome + '</td>';mdata += '<td>'+value.netIncome + '</td>';mdata += '<td>'+value.researchAndDevelopment + '</td>';mdata += '<td>'+value.operatingExpense + '</td>';mdata += '<td>'+value.currentAssets + '</td>';mdata += '<td>'+value.totalAssets + '</td>';mdata += '<td>'+value.totalLiabilities + '</td>';mdata += '<td>'+value.currentCash + '</td>';mdata += '<td>'+value.currentDebt + '</td>';mdata += '<td>'+value.totalCash + '</td>';mdata += '<td>'+value.totalDebt + '</td>';mdata += '<td>'+value.shareholderEquity + '</td>';mdata += '<td>'+value.cashChange + '</td>';mdata += '<td>'+value.cashFlow + '</td>';mdata += '<td>'+value.operatingGainsLosses + '</td>';mdata += '</tr>';});mdata += "</tbody></table>";displayResources.html(mdata);$("table").addClass("table");});});


$("#retrieve-financials-Nordstrom").click(function(){var displayResources = $("#display-financials-Nordstrom");+displayResources.text("Loading data from JSON source...");$.getJSON("https://api.iextrading.com/1.0/stock/JWN/financials?period=annual", function (data) {var mdata ="<table><thead><tr><th>symbol</th><th>reportDate</th><th>grossProfit</th><th>costOfRevenue</th><th>operatingRevenue</th><th>totalRevenue</th><th>operatingIncome</th><th>netIncome</th><th>researchAndDevelopment</th><th>operatingExpense</th><th>currentAssets</th><th>totalAssets</th><th>totalLiabilities</th><th>currentCash</th><th>currentDebt</th><th>totalCash</th><th>totalDebt</th><th>shareholderEquity</th><th>cashChange</th><th>cashFlow</th><th>operatingGainsLosses</th></thead><tbody>";$.each(data['financials'], function (key, value) {mdata += '<tr>';mdata += '<td>'+data.symbol + '</td>';mdata += '<td>'+value.reportDate + '</td>';mdata += '<td>'+value.grossProfit + '</td>';mdata += '<td>'+value.costOfRevenue + '</td>';mdata += '<td>'+value.operatingRevenue + '</td>';mdata += '<td>'+value.totalRevenue + '</td>';mdata += '<td>'+value.operatingIncome + '</td>';mdata += '<td>'+value.netIncome + '</td>';mdata += '<td>'+value.researchAndDevelopment + '</td>';mdata += '<td>'+value.operatingExpense + '</td>';mdata += '<td>'+value.currentAssets + '</td>';mdata += '<td>'+value.totalAssets + '</td>';mdata += '<td>'+value.totalLiabilities + '</td>';mdata += '<td>'+value.currentCash + '</td>';mdata += '<td>'+value.currentDebt + '</td>';mdata += '<td>'+value.totalCash + '</td>';mdata += '<td>'+value.totalDebt + '</td>';mdata += '<td>'+value.shareholderEquity + '</td>';mdata += '<td>'+value.cashChange + '</td>';mdata += '<td>'+value.cashFlow + '</td>';mdata += '<td>'+value.operatingGainsLosses + '</td>';mdata += '</tr>';});mdata += "</tbody></table>";displayResources.html(mdata);$("table").addClass("table");});});


$("#retrieve-financials-ColumbiaSportswear").click(function(){var displayResources = $("#display-financials-ColumbiaSportswear");+displayResources.text("Loading data from JSON source...");$.getJSON("https://api.iextrading.com/1.0/stock/COLM/financials?period=annual", function (data) {var mdata ="<table><thead><tr><th>symbol</th><th>reportDate</th><th>grossProfit</th><th>costOfRevenue</th><th>operatingRevenue</th><th>totalRevenue</th><th>operatingIncome</th><th>netIncome</th><th>researchAndDevelopment</th><th>operatingExpense</th><th>currentAssets</th><th>totalAssets</th><th>totalLiabilities</th><th>currentCash</th><th>currentDebt</th><th>totalCash</th><th>totalDebt</th><th>shareholderEquity</th><th>cashChange</th><th>cashFlow</th><th>operatingGainsLosses</th></thead><tbody>";$.each(data['financials'], function (key, value) {mdata += '<tr>';mdata += '<td>'+data.symbol + '</td>';mdata += '<td>'+value.reportDate + '</td>';mdata += '<td>'+value.grossProfit + '</td>';mdata += '<td>'+value.costOfRevenue + '</td>';mdata += '<td>'+value.operatingRevenue + '</td>';mdata += '<td>'+value.totalRevenue + '</td>';mdata += '<td>'+value.operatingIncome + '</td>';mdata += '<td>'+value.netIncome + '</td>';mdata += '<td>'+value.researchAndDevelopment + '</td>';mdata += '<td>'+value.operatingExpense + '</td>';mdata += '<td>'+value.currentAssets + '</td>';mdata += '<td>'+value.totalAssets + '</td>';mdata += '<td>'+value.totalLiabilities + '</td>';mdata += '<td>'+value.currentCash + '</td>';mdata += '<td>'+value.currentDebt + '</td>';mdata += '<td>'+value.totalCash + '</td>';mdata += '<td>'+value.totalDebt + '</td>';mdata += '<td>'+value.shareholderEquity + '</td>';mdata += '<td>'+value.cashChange + '</td>';mdata += '<td>'+value.cashFlow + '</td>';mdata += '<td>'+value.operatingGainsLosses + '</td>';mdata += '</tr>';});mdata += "</tbody></table>";displayResources.html(mdata);$("table").addClass("table");});});


$("#retrieve-financials-JazzPharmaceuticals").click(function(){var displayResources = $("#display-financials-JazzPharmaceuticals");+displayResources.text("Loading data from JSON source...");$.getJSON("https://api.iextrading.com/1.0/stock/JAZZ/financials?period=annual", function (data) {var mdata ="<table><thead><tr><th>symbol</th><th>reportDate</th><th>grossProfit</th><th>costOfRevenue</th><th>operatingRevenue</th><th>totalRevenue</th><th>operatingIncome</th><th>netIncome</th><th>researchAndDevelopment</th><th>operatingExpense</th><th>currentAssets</th><th>totalAssets</th><th>totalLiabilities</th><th>currentCash</th><th>currentDebt</th><th>totalCash</th><th>totalDebt</th><th>shareholderEquity</th><th>cashChange</th><th>cashFlow</th><th>operatingGainsLosses</th></thead><tbody>";$.each(data['financials'], function (key, value) {mdata += '<tr>';mdata += '<td>'+data.symbol + '</td>';mdata += '<td>'+value.reportDate + '</td>';mdata += '<td>'+value.grossProfit + '</td>';mdata += '<td>'+value.costOfRevenue + '</td>';mdata += '<td>'+value.operatingRevenue + '</td>';mdata += '<td>'+value.totalRevenue + '</td>';mdata += '<td>'+value.operatingIncome + '</td>';mdata += '<td>'+value.netIncome + '</td>';mdata += '<td>'+value.researchAndDevelopment + '</td>';mdata += '<td>'+value.operatingExpense + '</td>';mdata += '<td>'+value.currentAssets + '</td>';mdata += '<td>'+value.totalAssets + '</td>';mdata += '<td>'+value.totalLiabilities + '</td>';mdata += '<td>'+value.currentCash + '</td>';mdata += '<td>'+value.currentDebt + '</td>';mdata += '<td>'+value.totalCash + '</td>';mdata += '<td>'+value.totalDebt + '</td>';mdata += '<td>'+value.shareholderEquity + '</td>';mdata += '<td>'+value.cashChange + '</td>';mdata += '<td>'+value.cashFlow + '</td>';mdata += '<td>'+value.operatingGainsLosses + '</td>';mdata += '</tr>';});mdata += "</tbody></table>";displayResources.html(mdata);$("table").addClass("table");});});


$("#retrieve-financials-BradyCorp").click(function(){var displayResources = $("#display-financials-BradyCorp");+displayResources.text("Loading data from JSON source...");$.getJSON("https://api.iextrading.com/1.0/stock/BRC/financials?period=annual", function (data) {var mdata ="<table><thead><tr><th>symbol</th><th>reportDate</th><th>grossProfit</th><th>costOfRevenue</th><th>operatingRevenue</th><th>totalRevenue</th><th>operatingIncome</th><th>netIncome</th><th>researchAndDevelopment</th><th>operatingExpense</th><th>currentAssets</th><th>totalAssets</th><th>totalLiabilities</th><th>currentCash</th><th>currentDebt</th><th>totalCash</th><th>totalDebt</th><th>shareholderEquity</th><th>cashChange</th><th>cashFlow</th><th>operatingGainsLosses</th></thead><tbody>";$.each(data['financials'], function (key, value) {mdata += '<tr>';mdata += '<td>'+data.symbol + '</td>';mdata += '<td>'+value.reportDate + '</td>';mdata += '<td>'+value.grossProfit + '</td>';mdata += '<td>'+value.costOfRevenue + '</td>';mdata += '<td>'+value.operatingRevenue + '</td>';mdata += '<td>'+value.totalRevenue + '</td>';mdata += '<td>'+value.operatingIncome + '</td>';mdata += '<td>'+value.netIncome + '</td>';mdata += '<td>'+value.researchAndDevelopment + '</td>';mdata += '<td>'+value.operatingExpense + '</td>';mdata += '<td>'+value.currentAssets + '</td>';mdata += '<td>'+value.totalAssets + '</td>';mdata += '<td>'+value.totalLiabilities + '</td>';mdata += '<td>'+value.currentCash + '</td>';mdata += '<td>'+value.currentDebt + '</td>';mdata += '<td>'+value.totalCash + '</td>';mdata += '<td>'+value.totalDebt + '</td>';mdata += '<td>'+value.shareholderEquity + '</td>';mdata += '<td>'+value.cashChange + '</td>';mdata += '<td>'+value.cashFlow + '</td>';mdata += '<td>'+value.operatingGainsLosses + '</td>';mdata += '</tr>';});mdata += "</tbody></table>";displayResources.html(mdata);$("table").addClass("table");});});
});
